const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const repoRoot = path.resolve(__dirname, "..");
const docPath = path.join(
  repoRoot,
  "docs",
  "DOMAIN_CONTRACTS_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY_v1.md",
);

const doc = fs.readFileSync(docPath, "utf8");

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertIncludesAll(haystack, values) {
  for (const value of values) {
    assert.match(haystack, new RegExp(escapeRegExp(value)), `missing required text: ${value}`);
  }
}

function assertDoesNotIncludeExactToken(haystack, token) {
  const tokenPattern = new RegExp(`(?<![A-Z0-9_])${escapeRegExp(token)}(?![A-Z0-9_])`);
  assert.doesNotMatch(haystack, tokenPattern, `forbidden exact token present: ${token}`);
}

function sectionBetween(heading, nextHeading) {
  const start = doc.indexOf(heading);
  assert.notEqual(start, -1, `missing section: ${heading}`);
  const afterStart = start + heading.length;
  const end = nextHeading ? doc.indexOf(nextHeading, afterStart) : doc.length;
  assert.notEqual(end, -1, `missing next section: ${nextHeading}`);
  return doc.slice(afterStart, end);
}

test("boundary doc exists and identity/status tokens are frozen", () => {
  assert.ok(fs.existsSync(docPath), "boundary doc must exist");
  assertIncludesAll(doc, [
    "Status-Family Post-Status-Preservation Blocker-Visibility No-Closure Consistency Scope After Status-Family Post-Wording-Consistency No-Overclaim Status Preservation Scope Boundary v1",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_ONLY",
    "DOCS_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_PARTIAL_GAP_CONTEXT",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_NON_AUTHORIZING",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_REVIEW_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BLOCKER_VISIBILITY_NO_CLOSURE_REVIEW_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_NO_OVERCLAIM_CONSISTENCY_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_STATUS_PRESERVATION_REVIEW_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_CONSISTENCY_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_VERIFICATION_ONLY",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_TOKEN_VOCABULARY_ONLY",
    "BLOCKER_VISIBILITY_NO_CLOSURE_REVIEW_ONLY",
    "NO_OVERCLAIM_CONSISTENCY_ONLY",
    "STATUS_PRESERVATION_REVIEW_ONLY",
    "VISIBLE_BLOCKERS_ARE_NOT_BLOCKER_CLOSURE",
    "VISIBLE_DEPENDENCIES_ARE_NOT_DEPENDENCY_CLOSURE",
    "FUTURE_PROOF_TEST_NEEDS_ARE_NOT_PROOF",
    "VALIDATION_POSTURE_IS_NOT_TECHNICAL_EVIDENCE_OR_CI_EVIDENCE",
    "FOCUSED_PROOF_OUTPUT_IS_TESTED_SCENARIO_VALIDATION_ONLY",
    "IMPLEMENTATION_EVIDENCE_ABSENCE_REMAINS_ABSENCE",
    "CLOSURE_CRITERIA_ARE_NOT_MET",
    "NO_IMPLEMENTATION_READINESS_AUTHORIZATION",
    "NO_PRODUCT_EXTERNAL_USE_DELIVERY_PACKET_READINESS",
    "NO_FINDINGS_SEVERITY_REMEDIATION_CLOSURE_LANGUAGE",
    "NO_BLOCKER_RESOLUTION",
    "NO_DEPENDENCY_CLOSURE",
    "NO_NEW_TOKEN_GROUPS",
    "NO_NEW_STATUS_FAMILIES",
    "NO_TOKEN_APPLICATION",
    "NO_STATUS_APPLICATION",
    "NO_ACTUAL_LABEL_APPLICATION",
    "NO_APPLIED_STATUS_LABELS",
    "NO_RUNTIME_PRODUCT_DELIVERY_STATUS_APPLICATION",
    "NO_ROUTE_BEHAVIOR_OR_ROUTE_EXECUTION",
    "NO_TECHNICAL_EVIDENCE_CREATED",
    "NO_CI_EVIDENCE_CREATED",
    "TESTED_SCENARIO_EVIDENCE_NOT_RUNTIME_CERTAINTY",
    "DOCS_ONLY_BOUNDARIES_REMAIN_NOT_RUNTIME_ENFORCEMENT",
    "LOCAL_LOGS_NOT_CI_EVIDENCE",
    "GENERATED_PDF_NOT_REPO_EVIDENCE",
    "PRODUCT_CANDIDATE_REMAINS_NONE",
    "EXTERNAL_USE_REMAINS_UNAUTHORIZED",
    "HUMAN_PROFESSIONAL_REVIEW_REQUIRED",
    "STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_CONTINUED_PAUSE",
  ]);
});

test("required sections preserve purpose, hierarchy, state, and prior review result", () => {
  assertIncludesAll(sectionBetween("## Purpose", "## Source Hierarchy"), [
    "completed read-only status-family post-status-preservation blocker-visibility/no-closure consistency scope review",
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY",
    "blocker-visibility/no-closure-review-only",
    "no-overclaim-consistency-only",
    "status-preservation-review-only",
    "consistency-only",
    "verification-only",
    "token-vocabulary-only",
    "does not close blockers or dependencies",
    "creates no implementation-readiness",
    "technical evidence, CI evidence",
    "token/status application, labels, routes, wording, examples, candidates",
  ]);

  assertIncludesAll(sectionBetween("## Source Hierarchy", "## Current Accepted State"), [
    "LIVE_REPO_EVIDENCE_WINS",
    "TRACKED_REPO_EVIDENCE_CONTROLS_CURRENT_STATE",
    "NEW_THREAD_HANDOFF_FILE_IS_CONTEXT_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY_CONTROLS_CURRENT_STATUS_PRESERVATION_CONTEXT",
    "STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_CONSISTENCY_STATUS_TOKEN_APPLICATION_RISK_SCOPE_BOUNDARY_CONTROLS_CURRENT_WORDING_COMMUNICATION_CONTEXT",
    "STATUS_FAMILY_POST_CONSISTENCY_STATUS_TOKEN_APPLICATION_RISK_SCOPE_AFTER_STATUS_FAMILY_POST_TOKEN_NORMALIZATION_NO_OVERCLAIM_CONSISTENCY_SCOPE_BOUNDARY_CONTROLS_CURRENT_APPLICATION_RISK_CONTEXT",
    "STATUS_FAMILY_POST_TOKEN_NORMALIZATION_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_CANONICAL_TOKEN_SET_SCOPE_BOUNDARY_CONTROLS_CURRENT_POST_TOKEN_CONTEXT",
    "STATUS_FAMILY_CANONICAL_TOKEN_SET_SCOPE_AFTER_STATUS_FAMILY_NO_OVERCLAIM_USAGE_RULE_SCOPE_BOUNDARY_CONTROLS_CURRENT_CANONICAL_TOKEN_SET_CONTEXT",
    "STATUS_FAMILY_NO_OVERCLAIM_USAGE_RULE_SCOPE_AFTER_STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_BOUNDARY_CONTROLS_CURRENT_USAGE_RULE_CONTEXT",
    "STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_AFTER_NO_OVERCLAIM_CONSISTENCY_SCOPE_BOUNDARY_CONTROLS_CURRENT_REPAIRED_LABEL_SET_CONTEXT",
    "STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_SUPERSEDES_50672e0_WITH_8d22d37",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY_CONTROLS_CURRENT_NOCS_CONTEXT",
    "FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_AFTER_REVIEW_ROUTE_STATUS_LABEL_SCOPE_BOUNDARY_CONTROLS_CURRENT_FCSL_CONTEXT",
    "REVIEW_ROUTE_STATUS_LABEL_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_BOUNDARY_CONTROLS_CURRENT_RRSL_CONTEXT",
    "SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_AFTER_TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_BOUNDARY_CONTROLS_CURRENT_VOCABULARY_CONTEXT",
    "TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_SCOPE_BOUNDARY_CONTROLS_CURRENT_TEV_CONTEXT",
    "D007_CI_RELEASE_PRODUCT_EXTERNAL_USE_POSTURE_AFTER_LOCAL_SANITIZED_TEST_MATERIAL_PILOT_SCOPE_BOUNDARY_CONTROLS_CURRENT_D007_CONTEXT",
    "DATA_HANDLING_SECURITY_CONTROL_PLANE_IMPLEMENTATION_CONTROL_PLAN_AFTER_DHC_ALIGNMENT_BOUNDARY_CONTROLS_CURRENT_DATA_HANDLING_CONTEXT",
    "TECHNICAL_VERIFICATION_NO_RAW_TRACE_CONTEXT_IS_ADVISORY_CONTEXT_ONLY",
    "FAILURE_MODE_REGISTER_USED_AS_NO_OVERCLAIM_CONTEXT_ONLY",
    "EXTERNAL_REVIEW_REQUIREMENTS_USED_AS_ADVISORY_CONTEXT_ONLY",
    "OLD_HANDOFF_FILES_ARE_HISTORICAL_CONTEXT_ONLY",
    "STALE_HANDOFF_MUST_NOT_SELECT_REOPEN_OR_CLOSE_SLICE",
  ]);

  assertIncludesAll(sectionBetween("## Current Accepted State", "## Prior Read-Only Review Result"), [
    "13cb103",
    "7481722",
    "8d17867 docs(context): refresh new-thread handoff after wording communication consistency boundary",
    "6081a34",
    "8fc08e1 docs(context): refresh new-thread handoff after status-token application-risk boundary",
    "ec41880",
    "8456227 docs(context): refresh new-thread handoff after post-token normalization consistency boundary",
    "a110bb8",
    "0898c72 docs(context): refresh new-thread handoff after status-family canonical token-set boundary",
    "53d0401 docs(domain): freeze status-family canonical token-set scope",
    "c399e91 docs(context): refresh new-thread handoff after status-family usage-rule boundary",
    "f3345d1",
    "8d22d37",
    "77a7100 docs(context): refresh new-thread handoff after repaired status-family label-set boundary",
    "50672e0",
    "5b49934 docs(domain): freeze no-overclaim consistency scope after fail-closed status-label family boundary",
    "be1f35d docs(domain): freeze fail-closed status-label family scope after review-route status-label boundary",
    "8e2ac5f docs(domain): freeze review-route status-label scope after synthetic vocabulary boundary",
    "ee998b0 docs(domain): freeze synthetic input output candidate vocabulary scope after technical evidence verification boundary",
    "7fa91be docs(domain): freeze technical evidence verification scope after synthetic candidate scope boundary",
    "6ac88d9 docs(domain): freeze synthetic input output candidate scope after D007 posture boundary",
    "7cadab0 docs(domain): freeze D007 CI release product external-use posture after local sanitized pilot scope boundary",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AND_HANDOFF_REVIEWED_AND_PAUSED_NO_CHANGE",
    "REVIEW_ONLY_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_COMPLETED_NO_CHANGE",
    "continued pause",
  ]);

  assertIncludesAll(sectionBetween("## Prior Read-Only Review Result", "## SF-BLOCKVIS Matrix"), [
    "REVIEW_ONLY status-family post-status-preservation blocker-visibility/no-closure consistency scope",
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY",
    "future DOCS_ONLY status-family post-status-preservation blocker-visibility/no-closure consistency boundary is suitable",
    "freezes that partial/gap result only",
    "does not close blockers",
    "does not close dependencies",
    "does not create evidence, CI evidence, implementation-readiness, implementation evidence",
  ]);
});

test("SF-BLOCKVIS matrix includes all required rows", () => {
  const matrix = sectionBetween("## SF-BLOCKVIS Matrix", "## Required Row Content");
  assertIncludesAll(matrix, [
    "| row ID | blocker-visibility/no-closure consistency surface | current tracked evidence level | relation to status-preservation boundary, wording/communication consistency boundary, status-token application-risk boundary, post-token-normalization consistency boundary, canonical-token-set boundary, usage-rule boundary, repaired label-set boundary, no-overclaim consistency boundary, fail-closed status-label family boundary, review-route/status-label boundary, vocabulary boundary, TEV boundary, D007 posture, data-handling blockers, and evidence digest | overclaim risk | current blocker/status | required future evidence if separately authorized | minimum future proof tests if separately authorized | what remains non-authorized |",
    "Every row preserves DOCS_ONLY review only",
    "blocker-visibility/no-closure-review-only",
    "no-overclaim-consistency-only",
    "status-preservation-review-only",
    "token-vocabulary-only",
    "no blocker closure",
    "no dependency closure",
    "no implementation-readiness",
    "no technical evidence creation",
    "no CI evidence",
    "no new token groups",
    "no new status families",
    "no token application",
    "no status application",
    "no route creation",
    "no route execution",
    "continued pause",
  ]);

  for (let index = 1; index <= 30; index += 1) {
    assertIncludesAll(matrix, [`SF-BLOCKVIS-${String(index).padStart(3, "0")}`]);
  }
});

test("required row content and summary preserve blocker visibility without closure", () => {
  assertIncludesAll(sectionBetween("## Required Row Content", "## Blocker-Visibility/No-Closure Consistency Scope Summary"), [
    "Planning posture remains DOCS_ONLY partial/gap after status-preservation scope.",
    "Blocker-visibility/no-closure-review-only means checking that visible blockers and dependencies stay visible without closure.",
    "No-overclaim-consistency-only means checking that future proof-test needs, validation posture, and status-preservation posture are not overread as proof, evidence, closure, implementation-readiness, or authorization.",
    "Visible blockers are not blocker closure.",
    "Visible dependencies are not dependency closure.",
    "Future proof-test needs are not proof.",
    "Validation posture is not technical evidence or CI evidence.",
    "Focused proof output is tested-scenario validation only.",
    "Implementation evidence absence remains absence.",
    "Closure criteria are not met.",
    "No implementation-readiness authorization is created.",
    "No implementation or runtime/API/schema/package behavior is created.",
    "No product/external-use/delivery/packet readiness is created.",
    "No findings/severity/remediation/closure language is created.",
    "No blocker resolution or dependency closure is created.",
    "No new token groups or status families are defined.",
    "No token application or status application is created.",
    "No actual labels or applied status labels are created.",
    "No runtime/product/delivery status application is created.",
    "No route behavior or route execution is created.",
    "No External Reviewer-facing wording, external-use wording, product language, delivery communication, or packet wording is created.",
    "No examples, candidates, actual test material, pilot execution, or real private run are selected or authorized.",
    "No local-log/source/private/material/metadata inspection or metadata acquisition is authorized.",
    "Local logs/PDF/evidence limits remain controlling.",
    "D001-D007/data-handling blocker visibility remains visible and unresolved/not closed.",
    "D007 non-authorization remains controlling.",
    "TEV/no-overclaim and tested-scenario-not-runtime-certainty remain controlling.",
    "Vocabulary, RRSL, FCSL, repaired label-set, usage-rule, canonical-token-set, post-token, application-risk, wording, and status-preservation chain remain controlling.",
    "Human/professional review gate remains preserved without approval or sign-off.",
    "Non-authorization and continued pause remain controlling.",
  ]);

  assertIncludesAll(sectionBetween("## Blocker-Visibility/No-Closure Consistency Scope Summary", "## Required Non-Authorizations"), [
    "next suitable review-only surface after status-family post-wording-consistency no-overclaim/status-preservation scope",
    "blocker-visibility/no-closure-review-only",
    "no-overclaim-consistency-only",
    "status-preservation-review-only",
    "consistency-only",
    "verification-only",
    "token-vocabulary-only",
    "closes no blockers",
    "closes no dependencies",
    "creates no implementation-readiness",
    "creates no implementation evidence",
    "creates no technical evidence or CI evidence",
    "creates no runtime certainty",
    "creates no release approval",
    "creates no product candidate, external-use, delivery, or packet approval",
    "defines no new token groups",
    "defines no new status families",
    "applies no token",
    "applies no status",
    "without actual labels",
    "without applied status labels",
    "without runtime/product/delivery status application",
    "without route creation or route execution",
    "without drafting or sending External Reviewer-facing wording",
    "without creating external-use wording",
    "without creating product/delivery/packet wording",
    "without creating finding/severity/remediation/closure wording",
    "without examples, candidates, or actual test material",
    "without pilot execution or real private run",
    "without local-log/source/metadata inspection",
    "preserves no metadata acquisition",
    "preserves blocker visibility without blocker closure",
    "preserves dependency visibility without dependency closure",
    "preserves future proof-test needs as future-only",
    "preserves validation posture as non-evidence",
    "preserves D007 non-authorization",
    "preserves TEV no-overclaim rules",
    "preserves vocabulary-only no-example/no-selection rules",
    "preserves review-route/status-label no-route/no-execution rules",
    "preserves fail-closed status-family-only no-actual-label-application rules",
    "preserves repaired allowed/prohibited label-set family-set-only rules",
    "preserves status-family no-overclaim usage-rule rules",
    "preserves canonical-token-set token-normalization-only rules",
    "preserves post-token-normalization consistency no-new-token-groups rules",
    "preserves status-token application-risk no-token-application rules",
    "preserves wording/communication consistency no-wording-creation rules",
    "preserves status-preservation no-new-status-families/no-status-application rules",
    "preserves no-overclaim consistency validation-not-evidence rules",
    "preserves tested-scenario evidence, not runtime certainty",
    "preserves DOCS_ONLY boundaries not runtime enforcement",
    "preserves product candidate none and external-use unauthorized",
    "preserves human/professional review as release gate",
    "No implementation-readiness authorization is created now.",
    "No implementation is created now.",
    "No blocker or dependency is closed now.",
    "Blocker-visibility/no-closure consistency scope cannot be closed now.",
  ]);
});

test("non-authorizations, evidence limits, no-overclaim, External Reviewer, and next posture stay bounded", () => {
  assertIncludesAll(sectionBetween("## Required Non-Authorizations", "## Evidence Limits"), [
    "blocker resolution",
    "blocker closure",
    "dependency closure",
    "implementation-readiness",
    "implementation evidence",
    "implementation",
    "runtime behavior",
    "runtime/API/schema/package behavior change",
    "technical evidence creation",
    "CI evidence",
    "test output capture",
    "log capture",
    "local log inspection",
    "local logs as CI evidence",
    "local logs as packet components",
    "raw/private/source inspection",
    "source package inspection",
    "PDF/image/screenshot/metadata inspection",
    "metadata acquisition",
    "new token groups",
    "new status families",
    "token application",
    "status application",
    "actual label application",
    "applied status labels",
    "actual status application",
    "runtime status application",
    "product status application",
    "delivery status application",
    "actual review-route creation",
    "review-route execution",
    "route creation",
    "route execution",
    "runtime route creation",
    "workflow route creation",
    "schema route creation",
    "delivery route creation",
    "packet route creation",
    "product/external-use route creation",
    "candidate route creation",
    "External Reviewer-facing wording",
    "external-use wording",
    "product language",
    "delivery communication",
    "packet wording",
    "finding wording",
    "severity wording",
    "remediation wording",
    "closure wording",
    "blocker-resolution wording",
    "examples",
    "candidate examples",
    "candidate example selection",
    "example candidate text",
    "synthetic input/output candidate selection",
    "actual test-material selection",
    "local sanitized test pilot authorization",
    "local sanitized test pilot execution",
    "real private run",
    "runtime certification",
    "technical sign-off",
    "release approval",
    "External Reviewer approval",
    "product candidate",
    "external-use authorization",
    "delivery to External Reviewer",
    "packet approval",
    "packet component approval",
    "final delivery decision",
    "PDF packet",
    "generated PDF as repo evidence",
    "generated PDF as packet component",
    "archive/ZIP",
    "PDF generation",
    "ZIP generation",
    "legal conclusion",
    "clinical conclusion",
    "evidentiary conclusion",
    "case-truth conclusion",
    "credibility finding",
    "risk score",
    "sufficiency score",
    "police report",
    "pleading",
    "finding",
    "severity",
    "remediation",
    "None are authorized by this boundary.",
  ]);

  assertIncludesAll(sectionBetween("## Evidence Limits", "## No-Overclaim Rules"), [
    "Blocker-visibility/no-closure boundary is not blocker closure.",
    "Blocker-visibility/no-closure boundary is not dependency closure.",
    "Blocker-visibility/no-closure boundary is not implementation-readiness.",
    "Blocker-visibility/no-closure boundary is not implementation evidence.",
    "Blocker-visibility/no-closure boundary is not implementation.",
    "Blocker-visibility/no-closure boundary is not runtime/API/schema/package behavior.",
    "Blocker-visibility/no-closure boundary is not technical evidence.",
    "Blocker-visibility/no-closure boundary is not CI evidence.",
    "Blocker-visibility/no-closure boundary is not release approval.",
    "Blocker-visibility/no-closure boundary is not runtime certification.",
    "Blocker-visibility/no-closure boundary is not technical sign-off.",
    "Blocker-visibility/no-closure boundary is not External Reviewer approval.",
    "Blocker-visibility/no-closure boundary is not product candidate.",
    "Blocker-visibility/no-closure boundary is not external-use authorization.",
    "Blocker-visibility/no-closure boundary is not delivery authorization.",
    "Blocker-visibility/no-closure boundary is not finding, severity, remediation, or closure.",
    "Blocker-visibility/no-closure boundary is not new token groups.",
    "Blocker-visibility/no-closure boundary is not new status families.",
    "Blocker-visibility/no-closure boundary is not token application.",
    "Blocker-visibility/no-closure boundary is not status application.",
    "Blocker-visibility/no-closure boundary is not actual label creation.",
    "Blocker-visibility/no-closure boundary is not applied status.",
    "Blocker-visibility/no-closure boundary is not route behavior.",
    "Visible blocker means visible blocker, not resolved blocker.",
    "Visible dependency means visible dependency, not closed dependency.",
    "Future proof-test need means future-only need, not proof.",
    "Validation output for this doc-freeze slice is not CI evidence.",
    "Test evidence remains tested-scenario evidence, not runtime certainty.",
    "Green tests do not mean release approval.",
    "Local logs are not CI evidence.",
    "Local logs are not packet components.",
    "Generated PDF is not repo evidence.",
    "Generated PDF is not packet component.",
    "DOCS_ONLY boundaries are not runtime enforcement.",
    "Product candidate requires separate explicit selection.",
    "External-use requires separate explicit authorization.",
    "Human/professional review remains release gate.",
    "Continued pause is valid.",
  ]);

  assertIncludesAll(sectionBetween("## No-Overclaim Rules", "## External Reviewer Posture"), [
    "Blocker visibility does not close blockers.",
    "Dependency visibility does not close dependencies.",
    "Future proof-test needs do not mean proof tests exist.",
    "Validation posture does not mean technical evidence.",
    "Validation posture does not mean CI evidence.",
    "Focused proof output does not mean runtime certainty.",
    "Implementation evidence absence does not mean implementation evidence exists.",
    "Closure criteria do not mean closure.",
    "Unresolved blocker does not mean remediation recommendation.",
    "Data-handling blocker visibility does not mean data-handling blocker closure.",
    "D001-D007 visibility does not close D001-D007.",
    "D007 non-authorization does not mean product/external-use readiness.",
    "TEV no-overclaim does not mean runtime certification.",
    "Human/professional review gate does not mean approval/sign-off.",
    "Status-preservation posture does not create status application.",
    "Token vocabulary does not create token application.",
    "No-overclaim consistency does not create evidence.",
    "Any future blocker closure requires separate explicit authorization and closure evidence.",
    "Any future dependency closure requires separate explicit authorization and closure evidence.",
    "Any future implementation-readiness authorization requires separate explicit authorization.",
    "Any future implementation requires separate explicit authorization.",
    "Any future implementation evidence requires separate explicit implementation evidence.",
    "Any future technical evidence requires separate explicit evidence creation.",
    "Any future CI evidence requires separate explicit CI evidence creation.",
    "Any future release approval requires separate explicit release approval.",
    "Any future product candidate requires separate explicit selection.",
    "Any future external-use requires separate explicit authorization.",
    "Any future new token groups require separate explicit authorization.",
    "Any future new status families require separate explicit authorization.",
    "Any future token application requires separate explicit authorization.",
    "Any future status application requires separate explicit authorization.",
    "Any future actual labels require separate explicit authorization.",
    "Any future runtime/product/delivery status application requires separate explicit authorization.",
    "Any future route creation requires separate explicit authorization.",
    "Any future route execution requires separate explicit authorization.",
    "Any future External Reviewer-facing wording requires separate explicit authorization.",
    "Any future external-use wording requires separate explicit authorization.",
    "Any future product language requires separate explicit authorization.",
    "Any future delivery or packet wording requires separate explicit authorization.",
    "Any future finding/severity/remediation/closure wording requires separate explicit authorization.",
    "Any future candidate examples require separate explicit authorization.",
    "Any future candidate selection requires separate explicit authorization.",
    "Any future test-material selection requires separate explicit authorization.",
    "Any future pilot execution requires separate explicit authorization.",
  ]);

  assertIncludesAll(sectionBetween("## External Reviewer Posture", "## Recommended Next Posture"), [
    "No external-review request is required by this boundary.",
    "Should we freeze a DOCS_ONLY status-family post-status-preservation blocker-visibility/no-closure consistency boundary",
    "internal scope-control wording only",
    "not a External Reviewer-facing message",
    "external-review requirements remains advisory context only",
    "not approval, sign-off, implementation-readiness authorization",
    "blocker resolution, or dependency closure",
  ]);

  assertIncludesAll(sectionBetween("## Recommended Next Posture", null), [
    "REVIEW_ONLY_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY",
    "DOCS_ONLY_NEW_THREAD_HANDOFF_REFRESH_AFTER_STATUS_FAMILY_POST_STATUS_PRESERVATION_BLOCKER_VISIBILITY_NO_CLOSURE_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_BOUNDARY",
    "continued pause",
    "None are authorized by this boundary.",
  ]);
});

test("boundary rejects exact overclaiming tokens", () => {
  const forbiddenTokens = [
    "BLOCKER_VISIBILITY_CREATES_BLOCKER_CLOSURE",
    "BLOCKER_VISIBILITY_CLOSES_BLOCKERS",
    "BLOCKER_VISIBILITY_RESOLVES_BLOCKERS",
    "DEPENDENCY_VISIBILITY_CREATES_DEPENDENCY_CLOSURE",
    "DEPENDENCY_VISIBILITY_CLOSES_DEPENDENCIES",
    "FUTURE_PROOF_NEEDS_ARE_PROOF",
    "FUTURE_PROOF_TEST_NEEDS_CREATE_EVIDENCE",
    "VALIDATION_POSTURE_CREATES_TECHNICAL_EVIDENCE",
    "VALIDATION_POSTURE_CREATES_CI_EVIDENCE",
    "FOCUSED_PROOF_OUTPUT_CREATES_RUNTIME_CERTAINTY",
    "TESTED_SCENARIO_VALIDATION_CREATES_RUNTIME_CERTAINTY",
    "IMPLEMENTATION_EVIDENCE_EXISTS",
    "IMPLEMENTATION_READINESS_AUTHORIZED",
    "IMPLEMENTATION_AUTHORIZED",
    "IMPLEMENTATION_CREATED",
    "RUNTIME_API_SCHEMA_PACKAGE_BEHAVIOR_CHANGED",
    "RUNTIME_READY",
    "MODEL_RUNTIME_READY",
    "RELEASE_APPROVAL_CREATED",
    "RUNTIME_CERTIFICATION_CREATED",
    "TECHNICAL_SIGN_OFF_CREATED",
    "EXTERNAL_REVIEWER_APPROVAL_CREATED",
    "PRODUCT_CANDIDATE_SELECTED",
    "EXTERNAL_USE_AUTHORIZED",
    "DELIVERY_TO_EXTERNAL_REVIEWER_AUTHORIZED",
    "PACKET_APPROVAL_CREATED",
    "FINAL_DELIVERY_DECISION_CREATED",
    "PDF_PACKET_CREATED",
    "ARCHIVE_ZIP_CREATED",
    "PDF_CREATED",
    "ZIP_CREATED",
    "TECHNICAL_EVIDENCE_CREATED",
    "CI_EVIDENCE_EXISTS",
    "CI_EVIDENCE_CREATED",
    "TEST_OUTPUT_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOGS_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOG_INSPECTION_AUTHORIZED",
    "LOCAL_LOGS_ARE_CI_EVIDENCE",
    "LOCAL_LOGS_ARE_PACKET_COMPONENTS",
    "GENERATED_PDF_AS_REPO_EVIDENCE",
    "GENERATED_PDF_AS_PACKET_COMPONENT",
    "STATUS_PRESERVATION_CREATES_NEW_TOKEN_GROUPS",
    "STATUS_PRESERVATION_CREATES_NEW_STATUS_FAMILIES",
    "STATUS_PRESERVATION_APPLIES_TOKENS",
    "STATUS_PRESERVATION_APPLIES_STATUS",
    "STATUS_PRESERVATION_CREATES_ACTUAL_LABELS",
    "STATUS_PRESERVATION_APPLIES_STATUS_LABELS",
    "STATUS_PRESERVATION_APPLIES_RUNTIME_STATUS",
    "STATUS_PRESERVATION_APPLIES_PRODUCT_STATUS",
    "STATUS_PRESERVATION_APPLIES_DELIVERY_STATUS",
    "TOKEN_APPLICATION_CREATED",
    "TOKEN_APPLIED",
    "STATUS_APPLICATION_CREATED",
    "STATUS_APPLIED",
    "ACTUAL_LABEL_APPLIED",
    "RUNTIME_STATUS_APPLIED",
    "PRODUCT_STATUS_APPLIED",
    "DELIVERY_STATUS_APPLIED",
    "ACTUAL_REVIEW_ROUTE_CREATED",
    "REVIEW_ROUTE_EXECUTED",
    "RUNTIME_ROUTE_CREATED",
    "WORKFLOW_ROUTE_CREATED",
    "SCHEMA_ROUTE_CREATED",
    "DELIVERY_ROUTE_CREATED",
    "PACKET_ROUTE_CREATED",
    "PRODUCT_EXTERNAL_USE_ROUTE_CREATED",
    "CANDIDATE_ROUTE_CREATED",
    "EXTERNAL_REVIEWER_FACING_WORDING_CREATED",
    "EXTERNAL_REVIEWER_MESSAGE_CREATED",
    "EXTERNAL_REVIEWER_MESSAGE_SENT",
    "EXTERNAL_USE_WORDING_CREATED",
    "PRODUCT_LANGUAGE_CREATED",
    "DELIVERY_COMMUNICATION_CREATED",
    "PACKET_WORDING_CREATED",
    "FINDING_WORDING_CREATED",
    "SEVERITY_WORDING_CREATED",
    "REMEDIATION_WORDING_CREATED",
    "CLOSURE_WORDING_CREATED",
    "BLOCKER_RESOLUTION_WORDING_CREATED",
    "CANDIDATE_EXAMPLES_SELECTED",
    "CANDIDATE_EXAMPLES_INCLUDED",
    "EXAMPLE_CANDIDATE_TEXT_DEFINED",
    "SYNTHETIC_CANDIDATE_SELECTED",
    "ACTUAL_TEST_MATERIAL_SELECTED",
    "LOCAL_SANITIZED_TEST_PILOT_AUTHORIZED",
    "LOCAL_SANITIZED_TEST_PILOT_EXECUTED",
    "REAL_PRIVATE_RUN_AUTHORIZED",
    "REAL_PRIVATE_RUN_STARTED",
    "RAW_PRIVATE_SOURCE_INSPECTION_AUTHORIZED",
    "SOURCE_PACKAGE_INSPECTION_AUTHORIZED",
    "PDF_IMAGE_SCREENSHOT_METADATA_INSPECTION_AUTHORIZED",
    "METADATA_ACQUISITION_AUTHORIZED",
    "LEGAL_CONCLUSION_CREATED",
    "CLINICAL_CONCLUSION_CREATED",
    "EVIDENTIARY_CONCLUSION_CREATED",
    "CASE_TRUTH_CONCLUSION_CREATED",
    "CREDIBILITY_FINDING_CREATED",
    "RISK_SCORE_CREATED",
    "SUFFICIENCY_SCORE_CREATED",
    "POLICE_REPORT_CREATED",
    "PLEADING_CREATED",
    "BLOCKER_RESOLVED",
    "BLOCKER_CLOSED",
    "DEPENDENCY_CLOSED",
    "SECURITY_FINDING_CREATED",
    "VULNERABILITY_FINDING_CREATED",
    "SEVERITY_ASSIGNED",
    "REMEDIATION_RECOMMENDED",
    "REMEDIATION_IMPLEMENTED",
  ];

  for (const token of forbiddenTokens) {
    assertDoesNotIncludeExactToken(doc, token);
  }
});
