const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const docsPath = path.join(
  __dirname,
  "..",
  "docs",
  "DOMAIN_CONTRACTS_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY_v1.md",
);
const docsText = fs.readFileSync(docsPath, "utf8");

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertIncludesAll(entries, text = docsText) {
  for (const entry of entries) {
    assert.match(text, new RegExp(escapeRegExp(entry)), `missing ${entry}`);
  }
}

function assertDoesNotIncludeExactToken(entries, text = docsText) {
  for (const entry of entries) {
    const pattern = new RegExp(
      `(?<![A-Z0-9_])${escapeRegExp(entry)}(?![A-Z0-9_])`,
    );
    assert.doesNotMatch(text, pattern, `forbidden exact token ${entry}`);
  }
}

function sectionBetween(startHeading, endHeading) {
  const start = docsText.indexOf(startHeading);
  assert.notEqual(start, -1, `missing section ${startHeading}`);
  const end = endHeading
    ? docsText.indexOf(endHeading, start + startHeading.length)
    : docsText.length;
  assert.notEqual(end, -1, `missing end section ${endHeading}`);
  return docsText.slice(start, end);
}

const matrix = sectionBetween("## NOCS-FCSL Matrix", "## Required Row Content");
const rowContent = sectionBetween(
  "## Required Row Content",
  "## No-Overclaim Consistency Scope Summary After Fail-Closed Status-Label Family Scope",
);
const summary = sectionBetween(
  "## No-Overclaim Consistency Scope Summary After Fail-Closed Status-Label Family Scope",
  "## Required Non-Authorizations",
);
const nonAuthorizations = sectionBetween(
  "## Required Non-Authorizations",
  "## Evidence Limits",
);
const evidenceLimits = sectionBetween("## Evidence Limits", "## No-Overclaim Rules");
const noOverclaim = sectionBetween("## No-Overclaim Rules", "## External Reviewer Posture");
const externalReviewer = sectionBetween("## External Reviewer Posture", "## Recommended Next Posture");
const recommended = sectionBetween("## Recommended Next Posture");

test("boundary doc exists", () => {
  assert.equal(fs.existsSync(docsPath), true);
});

test("identity/status tokens exist", () => {
  assertIncludesAll([
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_ONLY",
    "DOCS_ONLY",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_PARTIAL_GAP_CONTEXT",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NON_AUTHORIZING",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_REVIEW_ONLY",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_VERIFICATION_ONLY",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_EVIDENCE_CREATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_CI_EVIDENCE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RUNTIME_CERTIFICATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_TECHNICAL_SIGN_OFF",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RELEASE_APPROVAL",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_EXTERNAL_REVIEWER_APPROVAL",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_PRODUCT_CANDIDATE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_EXTERNAL_USE_AUTHORIZATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_ACTUAL_LABEL_APPLICATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RUNTIME_STATUS_APPLICATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_PRODUCT_STATUS_APPLICATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_DELIVERY_STATUS_APPLICATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_ACTUAL_ROUTE_CREATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_ROUTE_EXECUTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_CANDIDATE_EXAMPLES",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_CANDIDATE_SELECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_ACTUAL_TEST_MATERIAL_SELECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_PILOT_EXECUTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_REAL_PRIVATE_RUN",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_LOCAL_LOG_INSPECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RAW_PRIVATE_SOURCE_INSPECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_SOURCE_PACKAGE_INSPECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_PDF_IMAGE_SCREENSHOT_METADATA_INSPECTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_METADATA_ACQUISITION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_IMPLEMENTATION_READINESS_AUTHORIZATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_IMPLEMENTATION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RUNTIME_BEHAVIOR",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_RUNTIME_API_SCHEMA_PACKAGE_BEHAVIOR_CHANGE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_BLOCKER_RESOLUTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NOT_DEPENDENCY_CLOSURE",
    "NO_OVERCLAIM_CONSISTENCY_REVIEW_ONLY",
    "VERIFICATION_ONLY",
    "NO_EVIDENCE_CREATED",
    "NO_CI_EVIDENCE_CREATED",
    "TESTED_SCENARIO_EVIDENCE_NOT_RUNTIME_CERTAINTY",
    "DOCS_ONLY_BOUNDARIES_REMAIN_NOT_RUNTIME_ENFORCEMENT",
    "PRODUCT_CANDIDATE_REMAINS_NONE",
    "EXTERNAL_USE_REMAINS_UNAUTHORIZED",
    "HUMAN_PROFESSIONAL_REVIEW_REQUIRED",
    "NO_ACTUAL_LABEL_APPLICATION",
    "NO_RUNTIME_STATUS_APPLICATION",
    "NO_PRODUCT_STATUS_APPLICATION",
    "NO_DELIVERY_STATUS_APPLICATION",
    "NO_ACTUAL_REVIEW_ROUTE_CREATED",
    "NO_REVIEW_ROUTE_EXECUTED",
    "NO_RUNTIME_ROUTE_CREATED",
    "NO_WORKFLOW_ROUTE_CREATED",
    "NO_SCHEMA_ROUTE_CREATED",
    "NO_DELIVERY_ROUTE_CREATED",
    "NO_PACKET_ROUTE_CREATED",
    "NO_PRODUCT_EXTERNAL_USE_ROUTE_CREATED",
    "NO_CANDIDATE_ROUTE_CREATED",
    "NO_CANDIDATE_EXAMPLES",
    "NO_CANDIDATE_EXAMPLE_SELECTION",
    "NO_EXAMPLE_CANDIDATE_TEXT",
    "NO_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_SELECTED",
    "NO_ACTUAL_TEST_MATERIAL_SELECTED",
    "PILOT_EXECUTION_REMAINS_UNAUTHORIZED",
    "REAL_PRIVATE_RUN_REMAINS_BLOCKED",
    "NO_LOCAL_LOG_INSPECTION",
    "LOCAL_LOGS_NOT_CI_EVIDENCE",
    "LOCAL_LOGS_NOT_PACKET_COMPONENTS",
    "NO_METADATA_ACQUISITION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_CONTINUED_PAUSE",
  ]);
});

test("purpose, source hierarchy, current state, and prior result exist", () => {
  assertIncludesAll([
    "This boundary freezes the completed read-only no-overclaim consistency scope review after fail-closed status-label family scope.",
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY",
    "This is no-overclaim consistency review only.",
    "This is verification-only and review-only.",
    "This boundary does not create or capture evidence.",
    "Validation for this slice is doc-freeze validation only, not CI evidence, not runtime certification, not technical sign-off, not release approval, and not product/external-use readiness.",
    "LIVE_REPO_EVIDENCE_WINS",
    "TRACKED_REPO_EVIDENCE_CONTROLS_CURRENT_STATE",
    "NEW_THREAD_HANDOFF_FILE_IS_CONTEXT_ONLY",
    "FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_AFTER_REVIEW_ROUTE_STATUS_LABEL_SCOPE_BOUNDARY_CONTROLS_CURRENT_FCSL_CONTEXT",
    "REVIEW_ROUTE_STATUS_LABEL_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_BOUNDARY_CONTROLS_CURRENT_RRSL_CONTEXT",
    "SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_AFTER_TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_BOUNDARY_CONTROLS_CURRENT_VOCABULARY_CONTEXT",
    "TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_SCOPE_BOUNDARY_CONTROLS_CURRENT_TEV_CONTEXT",
    "SYNTHETIC_INPUT_OUTPUT_CANDIDATE_SCOPE_AFTER_D007_CI_RELEASE_PRODUCT_EXTERNAL_USE_POSTURE_BOUNDARY_CONTROLS_CURRENT_CANDIDATE_SCOPE_CONTEXT",
    "D007_CI_RELEASE_PRODUCT_EXTERNAL_USE_POSTURE_AFTER_LOCAL_SANITIZED_TEST_MATERIAL_PILOT_SCOPE_BOUNDARY_CONTROLS_CURRENT_D007_CONTEXT",
    "LOCAL_SANITIZED_TEST_MATERIAL_PILOT_SCOPE_AFTER_RUNTIME_GATE_INVENTORY_POSTURE_BOUNDARY_CONTROLS_CURRENT_PILOT_SCOPE_CONTEXT",
    "RUNTIME_GATE_INVENTORY_POSTURE_AFTER_D005_THIRD_PARTY_PROVIDER_ROUTING_BOUNDARY_CONTROLS_CURRENT_D006_CONTEXT",
    "DATA_HANDLING_IMPLEMENTATION_CONTROL_PLAN_AFTER_DHC_ALIGNMENT_BOUNDARY_CONTROLS_CURRENT_DATA_HANDLING_CONTEXT",
    "TECHNICAL_VERIFICATION_NO_RAW_TRACE_CONTEXT_IS_ADVISORY_CONTEXT_ONLY",
    "FAILURE_MODE_REGISTER_USED_AS_NO_OVERCLAIM_CONTEXT_ONLY",
    "EXTERNAL_REVIEW_REQUIREMENTS_USED_AS_ADVISORY_CONTEXT_ONLY",
    "OLD_HANDOFF_FILES_ARE_HISTORICAL_CONTEXT_ONLY",
    "STALE_HANDOFF_MUST_NOT_SELECT_REOPEN_OR_CLOSE_SLICE",
    "409984b docs(context): refresh new-thread handoff after fail-closed status-label family boundary",
    "be1f35d docs(domain): freeze fail-closed status-label family scope after review-route status-label boundary",
    "8e2ac5f docs(domain): freeze review-route status-label scope after synthetic vocabulary boundary",
    "ee998b0 docs(domain): freeze synthetic input output candidate vocabulary scope after technical evidence verification boundary",
    "7fa91be docs(domain): freeze technical evidence verification scope after synthetic candidate scope boundary",
    "6ac88d9 docs(domain): freeze synthetic input output candidate scope after D007 posture boundary",
    "7cadab0 docs(domain): freeze D007 CI release product external-use posture after local sanitized pilot scope boundary",
    "4d6276e docs(domain): freeze local sanitized pilot scope after runtime gate inventory boundary",
    "78ceb94 docs(domain): freeze runtime gate inventory posture after D005 third-party routing boundary",
    "78c27b5 docs(domain): freeze D005 third-party/provider routing after D004 raw-material routing boundary",
    "4f26035 docs(domain): freeze D004 raw material routing after D003 retention deletion boundary",
    "4fd0b26 docs(domain): freeze D003 retention deletion after D002 audit boundary",
    "af1fd3b docs(domain): freeze D002 audit access log after D001 boundary",
    "21f8c0d docs(domain): freeze D001 RBAC admin support after data handling control plan boundary",
    "070133e docs(domain): freeze data handling control plan after DHC alignment boundary",
    "58c4e4f docs(domain): freeze DHC alignment after D001-D007 reprioritization boundary",
    "39c28ea docs(domain): freeze D001-D007 post-trust-spine reprioritization boundary",
    "FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_AND_HANDOFF_REVIEWED_AND_PAUSED_NO_CHANGE",
    "REVIEW_ONLY_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_COMPLETED_NO_CHANGE",
    "POST_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_NO_OVERCLAIM_CONSISTENCY_SCOPE_RECOMMENDATION_SELECTED_NO_CHANGE",
    "COMBINED_READ_ONLY_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_COMPLETED_NO_CHANGE",
    "REVIEW_ONLY no-overclaim consistency scope after fail-closed status-label family scope was performed.",
    "A future DOCS_ONLY no-overclaim consistency boundary is suitable.",
    "This boundary freezes that partial/gap result only.",
  ]);
});

test("NOCS-FCSL matrix exists and all rows exist", () => {
  assertIncludesAll([
    "row ID",
    "no-overclaim surface",
    "current tracked evidence level",
    "relation to fail-closed status-label family boundary, review-route/status-label boundary, vocabulary boundary, TEV boundary, D007 posture, and evidence digest",
    "overclaim risk",
    "current blocker/status",
    "required future evidence if separately authorized",
    "minimum future proof tests if separately authorized",
    "what remains non-authorized",
    "Every row preserves DOCS_ONLY review only",
  ], matrix);

  for (let index = 1; index <= 30; index += 1) {
    assertIncludesAll([`NOCS-FCSL-${String(index).padStart(3, "0")}`], matrix);
  }
});

test("required row content and summary exist", () => {
  assertIncludesAll([
    "Planning posture remains DOCS_ONLY partial/gap after fail-closed status-label family scope.",
    "Live git evidence wins over handoff/context text.",
    "Fail-closed status families are not actual labels and do not apply labels.",
    "Status families are not runtime, product, or delivery status application.",
    "Fail-closed labels are not implementation, enforcement, or decisions.",
    "Review-route/status-label scope still creates no routes and no execution.",
    "Vocabulary-only no-example/no-selection posture still controls.",
    "TEV remains no evidence, no CI, no runtime certification, no technical sign-off.",
    "D007 product/external-use non-authorization remains controlling.",
    "Local sanitized pilot-scope remains no execution and no real private run.",
    "Runtime-gate inventory remains posture only, not implementation.",
    "Data-handling blockers remain unresolved/not closed.",
    "Local logs are not CI evidence and not packet components.",
    "Generated PDF is not repo evidence and not packet component.",
    "Tested-scenario evidence is not runtime certainty.",
    "Green tests are not release approval.",
    "DOCS_ONLY boundaries are not runtime enforcement.",
    "Human/professional review remains release gate, not approval.",
    "Product candidate remains none and external-use remains unauthorized.",
    "Delivery/packet/final decision/PDF packet/archive/ZIP remain absent.",
    "Raw/private/source/source-package/media/metadata inspection remains prohibited.",
    "Metadata acquisition and local-log inspection remain prohibited.",
    "Technical evidence/CI/test-output/log capture remain prohibited.",
    "Legal/clinical/evidentiary/case-truth conclusions remain prohibited.",
    "Credibility/risk/sufficiency/police-report/pleading outputs remain prohibited.",
    "Findings/severity/remediation remain prohibited.",
    "Blocker/dependency closure remains prohibited.",
    "Implementation/implementation-readiness/runtime behavior remains absent.",
    "Future proof-test needs are future-only and do not mean proof exists.",
    "Non-authorization and continued pause remain controlling.",
  ], rowContent);

  assertIncludesAll([
    "no-overclaim consistency scope is the next suitable review-only surface after fail-closed status-label family scope",
    "it can remain verification-only and review-only",
    "it can be defined without creating/capturing evidence",
    "it can be defined without treating validation as CI evidence",
    "it can be defined without local logs",
    "it can be defined without raw/private/source/PDF/image/metadata inspection",
    "it can be defined without metadata acquisition",
    "it can be defined without actual label application",
    "it can be defined without status application in runtime/product/delivery context",
    "it can be defined without routes or route execution",
    "it can be defined without examples",
    "it can be defined without candidate selection",
    "it can be defined without actual test-material selection",
    "it can be defined without pilot execution or real private run",
    "it preserves D007 non-authorization",
    "it preserves TEV no-overclaim rules",
    "it preserves vocabulary-only no-example/no-selection rules",
    "it preserves review-route/status-label no-route/no-execution rules",
    "it preserves fail-closed status-family-only no-actual-label-application rules",
    "it preserves tested-scenario evidence, not runtime certainty",
    "it preserves DOCS_ONLY boundaries not runtime enforcement",
    "it preserves product candidate none and external-use unauthorized",
    "it preserves human/professional review as release gate",
    "no implementation-readiness authorization is created now",
    "no implementation is created now",
    "no technical evidence or CI evidence is created now",
    "no route, status application, label application, candidate, example, or test material is selected now",
    "no blocker or dependency is closed now",
    "no-overclaim consistency scope cannot be closed now",
  ], summary);
});

test("non-authorizations, evidence limits, and no-overclaim rules exist", () => {
  assertIncludesAll([
    "No authorization is created for technical evidence creation, CI evidence, test output capture, log capture",
    "actual label application",
    "runtime status application",
    "product status application",
    "delivery status application",
    "actual review-route creation",
    "review-route execution",
    "runtime route creation",
    "workflow route creation",
    "schema route creation",
    "delivery route creation",
    "packet route creation",
    "product/external-use route creation",
    "candidate route creation",
    "candidate examples",
    "candidate example selection",
    "example candidate text",
    "synthetic input/output candidate selection",
    "actual test-material selection",
    "local sanitized test pilot authorization",
    "local sanitized test pilot execution",
    "real private run",
    "runtime certification",
    "technical sign-off",
    "release approval",
    "External Reviewer approval",
    "product candidate",
    "external-use authorization",
    "delivery to External Reviewer",
    "packet approval",
    "packet component approval",
    "final delivery decision",
    "PDF packet",
    "generated PDF as repo evidence",
    "generated PDF as packet component",
    "archive/ZIP",
    "PDF generation",
    "ZIP generation",
    "raw/private/source inspection",
    "source package inspection",
    "PDF/image/screenshot/metadata inspection",
    "metadata acquisition",
    "implementation-readiness",
    "implementation",
    "runtime behavior",
    "runtime/API/schema/package behavior change",
    "legal conclusion",
    "clinical conclusion",
    "evidentiary conclusion",
    "case-truth conclusion",
    "credibility finding",
    "risk score",
    "sufficiency score",
    "police report",
    "pleading",
    "runtime gate implementation",
    "runtime gate movement",
    "validator dispatch",
    "registry/lookup",
    "schema enforcement creation",
    "workflow enforcement creation",
    "third-party/provider routing implementation or authorization",
    "provider integration",
    "provider registry",
    "data-routing map",
    "token/URL/secret handling",
    "raw-material routing implementation",
    "retention implementation",
    "deletion implementation",
    "audit/access-log implementation",
    "RBAC/access-control implementation",
    "DHC implementation",
    "DHC closure",
    "blocker resolution",
    "dependency closure",
    "finding",
    "severity",
    "remediation",
  ], nonAuthorizations);

  assertIncludesAll([
    "no-overclaim consistency boundary is not evidence creation",
    "no-overclaim consistency boundary is not CI evidence",
    "no-overclaim consistency boundary is not test-output capture",
    "no-overclaim consistency boundary is not log capture",
    "no-overclaim consistency boundary is not actual label application",
    "no-overclaim consistency boundary is not runtime status application",
    "no-overclaim consistency boundary is not product status application",
    "no-overclaim consistency boundary is not delivery status application",
    "no-overclaim consistency boundary is not route creation",
    "no-overclaim consistency boundary is not route execution",
    "no-overclaim consistency boundary is not candidate selection",
    "no-overclaim consistency boundary is not actual test-material selection",
    "no-overclaim consistency boundary is not pilot authorization",
    "no-overclaim consistency boundary is not real private run",
    "no-overclaim consistency boundary is not runtime certification",
    "no-overclaim consistency boundary is not technical sign-off",
    "no-overclaim consistency boundary is not release approval",
    "no-overclaim consistency boundary is not External Reviewer approval",
    "no-overclaim consistency boundary is not product candidate",
    "no-overclaim consistency boundary is not external-use authorization",
    "validation output for this doc-freeze slice is not CI evidence",
    "required CI does not mean CI exists",
    "required implementation evidence does not mean evidence exists",
    "test evidence remains tested-scenario evidence, not runtime certainty",
    "green tests do not mean release approval",
    "local logs are not CI evidence",
    "local logs are not packet components",
    "generated PDF is not repo evidence",
    "generated PDF is not packet component",
    "DOCS_ONLY boundaries are not runtime enforcement",
    "product candidate requires separate explicit selection",
    "external-use requires separate explicit authorization",
    "human/professional review remains release gate",
    "continued pause is valid",
  ], evidenceLimits);

  assertIncludesAll([
    "status families do not mean actual labels exist",
    "status families do not mean labels were applied",
    "status families do not mean runtime/product/delivery status application",
    "fail-closed labels do not mean implementation, enforcement, or decisions",
    "review-route/status-label rows do not create routes or route execution",
    "vocabulary rows do not create examples, candidates, or test material",
    "TEV/no-overclaim rows do not create technical evidence",
    "D007 non-authorization rows do not authorize D007",
    "tested-scenario rows do not create runtime certainty",
    "DOCS_ONLY rows do not create runtime enforcement",
    "human/professional review rows do not create approval",
    "product/external-use rows do not authorize product candidate or external-use",
    "delivery/packet rows do not authorize delivery, PDF packet, archive, or ZIP",
    "no local-log row does not mean local logs were inspected",
    "no raw/private/source row does not mean raw material was inspected",
    "no metadata row does not mean metadata was acquired",
    "future proof-test needs do not mean proof tests exist",
    "implementation evidence absence does not mean implementation evidence exists",
    "blocker visibility does not close blockers",
    "closure criteria do not mean closure",
    "any future actual label application requires separate explicit authorization",
    "any future runtime/product/delivery status application requires separate explicit authorization",
    "any future route creation requires separate explicit authorization",
    "any future route execution requires separate explicit authorization",
    "any future candidate examples require separate explicit authorization",
    "any future candidate selection requires separate explicit authorization",
    "any future test-material selection requires separate explicit authorization",
    "any future pilot execution requires separate explicit authorization",
    "any future technical evidence creation requires separate explicit authorization",
    "any future CI evidence requires separate explicit CI evidence creation",
    "any future release approval requires separate explicit release approval",
    "any future product candidate requires separate explicit selection",
    "any future external-use requires separate explicit authorization",
    "any future implementation-readiness authorization requires separate explicit authorization",
    "any future implementation requires separate explicit authorization",
  ], noOverclaim);
});

test("External Reviewer posture and recommended next posture exist", () => {
  assertIncludesAll([
    "No external-review request is required by this boundary.",
    "Should we freeze a DOCS_ONLY no-overclaim consistency boundary after fail-closed status-label family scope, preserving verification-only review with no labels/status application, routes, execution, examples, candidates, test material, pilot/private run, evidence/CI, logs, raw/private/source/media/metadata inspection, product/external-use, delivery, findings, remediation, blocker closure, or dependency closure?",
    "external-review requirements remains advisory context only, not approval",
  ], externalReviewer);

  assertIncludesAll([
    "REVIEW_ONLY_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY",
    "DOCS_ONLY_NEW_THREAD_HANDOFF_REFRESH_AFTER_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY",
    "continued pause",
    "None are authorized by this boundary.",
  ], recommended);
});

test("forbidden exact overclaiming tokens are absent", () => {
  assertDoesNotIncludeExactToken([
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_CREATES_TECHNICAL_EVIDENCE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_CREATES_CI_EVIDENCE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_CAPTURES_TEST_OUTPUT",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_CAPTURES_LOGS",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_APPLIES_ACTUAL_LABELS",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_APPLIES_RUNTIME_STATUS",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_APPLIES_PRODUCT_STATUS",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_APPLIES_DELIVERY_STATUS",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_CREATES_ACTUAL_ROUTES",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_EXECUTES_ROUTES",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_SELECTS_CANDIDATE_EXAMPLES",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_INCLUDES_CANDIDATE_EXAMPLES",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_DEFINES_EXAMPLE_CANDIDATE_TEXT",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_SELECTS_SYNTHETIC_CANDIDATE",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_SELECTS_ACTUAL_TEST_MATERIAL",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AUTHORIZES_PILOT_EXECUTION",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AUTHORIZES_REAL_PRIVATE_RUN",
    "ACTUAL_LABEL_APPLIED",
    "RUNTIME_STATUS_APPLIED",
    "PRODUCT_STATUS_APPLIED",
    "DELIVERY_STATUS_APPLIED",
    "ACTUAL_REVIEW_ROUTE_CREATED",
    "REVIEW_ROUTE_EXECUTED",
    "RUNTIME_ROUTE_CREATED",
    "WORKFLOW_ROUTE_CREATED",
    "SCHEMA_ROUTE_CREATED",
    "DELIVERY_ROUTE_CREATED",
    "PACKET_ROUTE_CREATED",
    "PRODUCT_EXTERNAL_USE_ROUTE_CREATED",
    "CANDIDATE_ROUTE_CREATED",
    "CANDIDATE_EXAMPLES_SELECTED",
    "CANDIDATE_EXAMPLES_INCLUDED",
    "EXAMPLE_CANDIDATE_TEXT_DEFINED",
    "SYNTHETIC_CANDIDATE_SELECTED",
    "ACTUAL_TEST_MATERIAL_SELECTED",
    "LOCAL_SANITIZED_TEST_PILOT_AUTHORIZED",
    "LOCAL_SANITIZED_TEST_PILOT_EXECUTED",
    "REAL_PRIVATE_RUN_AUTHORIZED",
    "REAL_PRIVATE_RUN_STARTED",
    "TECHNICAL_EVIDENCE_CREATED",
    "CI_EVIDENCE_EXISTS",
    "CI_EVIDENCE_CREATED",
    "TEST_OUTPUT_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOGS_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOG_INSPECTION_AUTHORIZED",
    "LOCAL_LOGS_ARE_CI_EVIDENCE",
    "LOCAL_LOGS_ARE_PACKET_COMPONENTS",
    "RAW_PRIVATE_SOURCE_INSPECTION_AUTHORIZED",
    "SOURCE_PACKAGE_INSPECTION_AUTHORIZED",
    "PDF_IMAGE_SCREENSHOT_METADATA_INSPECTION_AUTHORIZED",
    "METADATA_ACQUISITION_AUTHORIZED",
    "RELEASE_APPROVAL_CREATED",
    "RUNTIME_CERTIFICATION_CREATED",
    "TECHNICAL_SIGN_OFF_CREATED",
    "EXTERNAL_REVIEWER_APPROVAL_CREATED",
    "PRODUCT_CANDIDATE_SELECTED",
    "EXTERNAL_USE_AUTHORIZED",
    "DELIVERY_TO_EXTERNAL_REVIEWER_AUTHORIZED",
    "PACKET_APPROVAL_CREATED",
    "FINAL_DELIVERY_DECISION_CREATED",
    "PDF_PACKET_CREATED",
    "ARCHIVE_ZIP_CREATED",
    "PDF_CREATED",
    "ZIP_CREATED",
    "LEGAL_CONCLUSION_CREATED",
    "CLINICAL_CONCLUSION_CREATED",
    "EVIDENTIARY_CONCLUSION_CREATED",
    "CASE_TRUTH_CONCLUSION_CREATED",
    "CREDIBILITY_FINDING_CREATED",
    "RISK_SCORE_CREATED",
    "SUFFICIENCY_SCORE_CREATED",
    "POLICE_REPORT_CREATED",
    "PLEADING_CREATED",
    "IMPLEMENTATION_EVIDENCE_EXISTS",
    "TEST_EVIDENCE_EXISTS",
    "IMPLEMENTATION_READINESS_AUTHORIZED",
    "IMPLEMENTATION_AUTHORIZED",
    "RUNTIME_AUTHORIZED",
    "RUNTIME_READY",
    "MODEL_RUNTIME_READY",
    "MODEL_COMPLETE",
    "MODEL_COMPLETION_READY",
    "RUNTIME_GATE_IMPLEMENTED",
    "RUNTIME_GATE_MOVEMENT_AUTHORIZED",
    "VALIDATOR_DISPATCH_CREATED",
    "REGISTRY_LOOKUP_CREATED",
    "SCHEMA_ENFORCEMENT_CREATED",
    "WORKFLOW_ENFORCEMENT_CREATED",
    "THIRD_PARTY_ROUTING_AUTHORIZED",
    "THIRD_PARTY_ROUTING_IMPLEMENTED",
    "RAW_MATERIAL_ROUTING_IMPLEMENTED",
    "RETENTION_IMPLEMENTED",
    "DELETION_IMPLEMENTED",
    "AUDIT_ACCESS_LOG_IMPLEMENTED",
    "RBAC_IMPLEMENTED",
    "ACCESS_CONTROL_IMPLEMENTED",
    "DHC_IMPLEMENTED",
    "DHC_CLOSED",
    "D007_CLOSED",
    "BLOCKER_RESOLVED",
    "DEPENDENCY_CLOSED",
    "SECURITY_FINDING_CREATED",
    "VULNERABILITY_FINDING_CREATED",
    "SEVERITY_ASSIGNED",
    "REMEDIATION_RECOMMENDED",
    "REMEDIATION_IMPLEMENTED",
  ]);
});
