const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const repoRoot = path.resolve(__dirname, "..");
const docPath = path.join(
  repoRoot,
  "docs",
  "DOMAIN_CONTRACTS_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY_v1.md",
);

const doc = fs.readFileSync(docPath, "utf8");

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertIncludesAll(haystack, values) {
  for (const value of values) {
    assert.match(haystack, new RegExp(escapeRegExp(value)), `missing required text: ${value}`);
  }
}

function assertDoesNotIncludeExactToken(haystack, token) {
  const tokenPattern = new RegExp(`(?<![A-Z0-9_])${escapeRegExp(token)}(?![A-Z0-9_])`);
  assert.doesNotMatch(haystack, tokenPattern, `forbidden exact token present: ${token}`);
}

function sectionBetween(heading, nextHeading) {
  const start = doc.indexOf(heading);
  assert.notEqual(start, -1, `missing section: ${heading}`);
  const afterStart = start + heading.length;
  const end = nextHeading ? doc.indexOf(nextHeading, afterStart) : doc.length;
  assert.notEqual(end, -1, `missing next section: ${nextHeading}`);
  return doc.slice(afterStart, end);
}

test("boundary doc exists and identity/status tokens are frozen", () => {
  assert.ok(fs.existsSync(docPath), "boundary doc must exist");
  assertIncludesAll(doc, [
    "Status-Family Post-Wording-Consistency No-Overclaim Status Preservation Scope After Status-Family Post-Application-Risk Wording Communication Consistency Scope Boundary v1",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_ONLY",
    "DOCS_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_PARTIAL_GAP_CONTEXT",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_NON_AUTHORIZING",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_REVIEW_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_NO_OVERCLAIM_STATUS_PRESERVATION_REVIEW_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_STATUS_PRESERVATION_REVIEW_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_CONSISTENCY_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_VERIFICATION_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_TOKEN_VOCABULARY_ONLY",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_NO_NEW_TOKEN_GROUPS",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_NO_NEW_STATUS_FAMILIES",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_NO_TOKEN_APPLICATION",
    "NO_OVERCLAIM_STATUS_PRESERVATION_REVIEW_ONLY",
    "STATUS_PRESERVATION_REVIEW_ONLY",
    "PRESERVED_WORDING_STATUS_FAMILY_IS_VOCABULARY_ONLY",
    "NO_NEW_TOKEN_GROUPS",
    "NO_NEW_STATUS_FAMILIES",
    "NO_TOKEN_APPLICATION",
    "NO_STATUS_APPLICATION",
    "NO_ACTUAL_LABELS_OR_APPLIED_STATUS_LABELS",
    "NO_RUNTIME_PRODUCT_DELIVERY_STATUS_APPLICATION",
    "NO_ROUTE_BEHAVIOR_OR_ROUTE_EXECUTION",
    "NO_EVIDENCE_OR_CI_EVIDENCE",
    "NO_EXTERNAL_REVIEWER_FACING_WORDING_CREATION",
    "NO_EXTERNAL_USE_WORDING_CREATION",
    "NO_PRODUCT_LANGUAGE_CREATION",
    "NO_DELIVERY_COMMUNICATION_CREATION",
    "NO_PACKET_WORDING_CREATION",
    "NO_FINDING_SEVERITY_REMEDIATION_CLOSURE_WORDING_CREATION",
    "NO_ACTUAL_STATUS_APPLICATION",
    "TESTED_SCENARIO_EVIDENCE_NOT_RUNTIME_CERTAINTY",
    "DOCS_ONLY_BOUNDARIES_REMAIN_NOT_RUNTIME_ENFORCEMENT",
    "PRODUCT_CANDIDATE_REMAINS_NONE",
    "EXTERNAL_USE_REMAINS_UNAUTHORIZED",
    "HUMAN_PROFESSIONAL_REVIEW_REQUIRED",
    "STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_CONTINUED_PAUSE",
  ]);
});

test("required sections preserve purpose, hierarchy, state, and prior review result", () => {
  assertIncludesAll(sectionBetween("## Purpose", "## Source Hierarchy"), [
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY",
    "no-overclaim-status-preservation-review-only",
    "status-preservation-review-only",
    "consistency-only",
    "verification-only",
    "token-vocabulary-only",
    "defines no new token groups or status families",
    "applies no tokens and creates no status application",
    "creates no External Reviewer-facing wording",
    "creates no external-use wording",
    "creates no CI evidence",
    "creates no implementation",
  ]);

  assertIncludesAll(sectionBetween("## Source Hierarchy", "## Current Accepted State"), [
    "LIVE_REPO_EVIDENCE_WINS",
    "TRACKED_REPO_EVIDENCE_CONTROLS_CURRENT_STATE",
    "NEW_THREAD_HANDOFF_FILE_IS_CONTEXT_ONLY",
    "STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_POST_CONSISTENCY_STATUS_TOKEN_APPLICATION_RISK_SCOPE_BOUNDARY_CONTROLS_CURRENT_WORDING_COMMUNICATION_CONTEXT",
    "STATUS_FAMILY_POST_CONSISTENCY_STATUS_TOKEN_APPLICATION_RISK_SCOPE_AFTER_STATUS_FAMILY_POST_TOKEN_NORMALIZATION_NO_OVERCLAIM_CONSISTENCY_SCOPE_BOUNDARY_CONTROLS_CURRENT_APPLICATION_RISK_CONTEXT",
    "STATUS_FAMILY_POST_TOKEN_NORMALIZATION_NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_STATUS_FAMILY_CANONICAL_TOKEN_SET_SCOPE_BOUNDARY_CONTROLS_CURRENT_POST_TOKEN_CONTEXT",
    "STATUS_FAMILY_CANONICAL_TOKEN_SET_SCOPE_AFTER_STATUS_FAMILY_NO_OVERCLAIM_USAGE_RULE_SCOPE_BOUNDARY_CONTROLS_CURRENT_CANONICAL_TOKEN_SET_CONTEXT",
    "STATUS_FAMILY_NO_OVERCLAIM_USAGE_RULE_SCOPE_AFTER_STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_BOUNDARY_CONTROLS_CURRENT_USAGE_RULE_CONTEXT",
    "STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_AFTER_NO_OVERCLAIM_CONSISTENCY_SCOPE_BOUNDARY_CONTROLS_CURRENT_REPAIRED_LABEL_SET_CONTEXT",
    "STATUS_FAMILY_ALLOWED_PROHIBITED_LABEL_SET_SCOPE_SUPERSEDES_50672e0_WITH_8d22d37",
    "NO_OVERCLAIM_CONSISTENCY_SCOPE_AFTER_FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_BOUNDARY_CONTROLS_CURRENT_NOCS_CONTEXT",
    "FAIL_CLOSED_STATUS_LABEL_FAMILY_SCOPE_AFTER_REVIEW_ROUTE_STATUS_LABEL_SCOPE_BOUNDARY_CONTROLS_CURRENT_FCSL_CONTEXT",
    "REVIEW_ROUTE_STATUS_LABEL_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_BOUNDARY_CONTROLS_CURRENT_RRSL_CONTEXT",
    "SYNTHETIC_INPUT_OUTPUT_CANDIDATE_VOCABULARY_SCOPE_AFTER_TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_BOUNDARY_CONTROLS_CURRENT_VOCABULARY_CONTEXT",
    "TECHNICAL_EVIDENCE_VERIFICATION_SCOPE_AFTER_SYNTHETIC_INPUT_OUTPUT_CANDIDATE_SCOPE_BOUNDARY_CONTROLS_CURRENT_TEV_CONTEXT",
    "D007_CI_RELEASE_PRODUCT_EXTERNAL_USE_POSTURE_AFTER_LOCAL_SANITIZED_TEST_MATERIAL_PILOT_SCOPE_BOUNDARY_CONTROLS_CURRENT_D007_CONTEXT",
    "TECHNICAL_VERIFICATION_NO_RAW_TRACE_CONTEXT_IS_ADVISORY_CONTEXT_ONLY",
    "FAILURE_MODE_REGISTER_USED_AS_NO_OVERCLAIM_CONTEXT_ONLY",
    "EXTERNAL_REVIEW_REQUIREMENTS_USED_AS_ADVISORY_CONTEXT_ONLY",
    "STALE_HANDOFF_MUST_NOT_SELECT_REOPEN_OR_CLOSE_SLICE",
  ]);

  assertIncludesAll(sectionBetween("## Current Accepted State", "## Prior Read-Only Review Result"), [
    "8d17867",
    "6081a34",
    "8fc08e1 docs(context): refresh new-thread handoff after status-token application-risk boundary",
    "ec41880",
    "8456227 docs(context): refresh new-thread handoff after post-token normalization consistency boundary",
    "a110bb8",
    "0898c72 docs(context): refresh new-thread handoff after status-family canonical token-set boundary",
    "53d0401 docs(domain): freeze status-family canonical token-set scope",
    "c399e91 docs(context): refresh new-thread handoff after status-family usage-rule boundary",
    "f3345d1",
    "8d22d37",
    "77a7100 docs(context): refresh new-thread handoff after repaired status-family label-set boundary",
    "50672e0",
    "5b49934 docs(domain): freeze no-overclaim consistency scope after fail-closed status-label family boundary",
    "be1f35d docs(domain): freeze fail-closed status-label family scope after review-route status-label boundary",
    "8e2ac5f docs(domain): freeze review-route status-label scope after synthetic vocabulary boundary",
    "ee998b0 docs(domain): freeze synthetic input output candidate vocabulary scope after technical evidence verification boundary",
    "7fa91be docs(domain): freeze technical evidence verification scope after synthetic candidate scope boundary",
    "6ac88d9 docs(domain): freeze synthetic input output candidate scope after D007 posture boundary",
    "7cadab0 docs(domain): freeze D007 CI release product external-use posture after local sanitized pilot scope boundary",
    "STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_AND_HANDOFF_REVIEWED_AND_PAUSED_NO_CHANGE",
    "REVIEW_ONLY_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_COMPLETED_NO_CHANGE",
    "continued pause",
  ]);

  assertIncludesAll(sectionBetween("## Prior Read-Only Review Result", "## SF-STATUSPRES Matrix"), [
    "REVIEW_ONLY status-family post-wording-consistency no-overclaim/status-preservation scope",
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY",
    "future DOCS_ONLY status-family post-wording-consistency no-overclaim/status-preservation boundary is suitable",
    "freezes that partial/gap result only",
    "does not draft or send External Reviewer-facing wording",
    "does not create external-use wording",
    "does not create CI evidence",
    "blocker closure",
    "dependency closure",
  ]);
});

test("SF-STATUSPRES matrix includes all required rows", () => {
  const matrix = sectionBetween("## SF-STATUSPRES Matrix", "## Required Row Content");
  assertIncludesAll(matrix, [
    "| row ID | no-overclaim/status-preservation surface | current tracked evidence level | relation to wording/communication consistency boundary, status-token application-risk boundary, post-token-normalization consistency boundary, canonical-token-set boundary, usage-rule boundary, repaired status-family label-set boundary, no-overclaim consistency boundary, fail-closed status-label family boundary, review-route/status-label boundary, vocabulary boundary, TEV boundary, D007 posture, and evidence digest | overclaim risk | current blocker/status | required future evidence if separately authorized | minimum future proof tests if separately authorized | what remains non-authorized |",
    "Every row preserves DOCS_ONLY review only",
    "no-overclaim-status-preservation-review-only",
    "status-preservation-review-only",
    "token-vocabulary-only",
    "no new token groups",
    "no new status families",
    "no token application",
    "no status application",
    "no External Reviewer-facing wording drafted or sent",
    "no external-use wording",
    "no product/delivery/packet wording",
    "no finding/severity/remediation/closure wording",
    "continued pause",
  ]);

  for (let index = 1; index <= 30; index += 1) {
    assertIncludesAll(matrix, [`SF-STATUSPRES-${String(index).padStart(3, "0")}`]);
  }
});

test("required row content and summary preserve no-overclaim status-preservation posture", () => {
  assertIncludesAll(sectionBetween("## Required Row Content", "## No-Overclaim/Status-Preservation Scope Summary"), [
    "Planning posture remains DOCS_ONLY partial/gap after wording/communication consistency scope.",
    "No-overclaim-status-preservation-review-only means reviewing preserved wording/status families against overread as authorization or application.",
    "Status-preservation-review-only means preserving current negative status posture without creating status application.",
    "Preserved wording/status family remains vocabulary only.",
    "No new token groups or status families are defined.",
    "No token application or status application is created.",
    "No actual labels or applied status labels are created.",
    "No runtime/product/delivery status application is created.",
    "No route behavior or route execution is created.",
    "No evidence or CI evidence is created.",
    "No External Reviewer-facing wording, external-use wording, product language, delivery communication, packet wording, finding/severity/remediation/closure wording is created.",
    "No examples, candidates, or actual test material are selected.",
    "No pilot execution, real private run, log/source/metadata inspection, or metadata acquisition is authorized.",
    "No product/external-use/delivery/packet readiness is created.",
    "No findings, severity, remediation, blocker closure, or dependency closure is created.",
    "Allowed token group status-preservation review remains vocabulary-only.",
    "Prohibited token group status-preservation review remains overclaim-exclusion-only.",
    "Future-authorization-required group remains future-only.",
    "Non-evidence group remains non-evidence-only.",
    "Non-runtime/non-enforcement group remains non-runtime-only.",
    "No-route/no-execution group remains no-route/no-execution-only.",
    "No-example/no-candidate/no-material group remains no-selection-only.",
    "No-product/no-external-use/no-delivery group remains downstream non-authorization.",
    "No-finding/no-severity/no-remediation/no-closure group remains advisory-only.",
    "Wording/communication consistency, application-risk, post-token-normalization consistency, canonical-token-set, usage-rule, repaired label-set, FCSL, RRSL, vocabulary, TEV, and D007 rules remain controlling.",
    "Local logs/PDF/evidence limits remain controlling.",
    "Data-handling/D001-D007 blockers remain visible and unresolved/not closed.",
    "Future proof-test needs are future-only and do not mean proof exists.",
    "Non-authorization and continued pause remain controlling.",
  ]);

  assertIncludesAll(sectionBetween("## No-Overclaim/Status-Preservation Scope Summary", "## Required Non-Authorizations"), [
    "next suitable review-only surface after status-family post-application-risk wording/communication consistency scope",
    "no-overclaim-status-preservation-review-only",
    "status-preservation-review-only",
    "consistency-only",
    "verification-only",
    "token-vocabulary-only",
    "defines no new token groups",
    "defines no new status families",
    "applies no token",
    "applies no status",
    "without actual labels",
    "without applied status labels",
    "without actual status application",
    "without runtime/product/delivery status application",
    "without route creation or route execution",
    "without drafting or sending External Reviewer-facing wording",
    "without creating external-use wording",
    "without creating product/delivery/packet wording",
    "without creating finding/severity/remediation/closure wording",
    "without examples, candidate examples, or example candidate text",
    "without candidate selection",
    "without actual test-material selection",
    "without pilot execution or real private run",
    "without technical evidence creation or CI evidence",
    "without local-log/source/metadata inspection",
    "preserves no metadata acquisition",
    "preserves D007 non-authorization",
    "preserves TEV no-overclaim rules",
    "preserves vocabulary-only no-example/no-selection rules",
    "preserves review-route/status-label no-route/no-execution rules",
    "preserves fail-closed status-family-only no-actual-label-application rules",
    "preserves repaired allowed/prohibited label-set family-set-only rules",
    "preserves status-family no-overclaim usage-rule rules",
    "preserves canonical-token-set token-normalization-only rules",
    "preserves post-token-normalization consistency no-new-token-groups rules",
    "preserves status-token application-risk no-token-application rules",
    "preserves wording/communication consistency no-wording-creation rules",
    "preserves no-overclaim consistency validation-not-evidence rules",
    "preserves tested-scenario evidence, not runtime certainty",
    "preserves DOCS_ONLY boundaries not runtime enforcement",
    "preserves product candidate none and external-use unauthorized",
    "preserves human/professional review as release gate",
    "No implementation-readiness authorization is created now.",
    "No implementation is created now.",
    "No-overclaim/status-preservation scope cannot be closed now.",
  ]);
});

test("non-authorizations, evidence limits, no-overclaim, External Reviewer, and next posture stay bounded", () => {
  assertIncludesAll(sectionBetween("## Required Non-Authorizations", "## Evidence Limits"), [
    "new token groups",
    "new status families",
    "token application",
    "status application",
    "actual label application",
    "applied status labels",
    "actual status application",
    "runtime status application",
    "product status application",
    "delivery status application",
    "actual review-route creation",
    "review-route execution",
    "External Reviewer-facing wording",
    "external-use wording",
    "product language",
    "delivery communication",
    "packet wording",
    "finding wording",
    "severity wording",
    "remediation wording",
    "closure wording",
    "blocker-resolution wording",
    "technical evidence creation",
    "CI evidence",
    "test output capture",
    "local log inspection",
    "local logs as CI evidence",
    "local logs as packet components",
    "generated PDF as repo evidence",
    "generated PDF as packet component",
    "implementation-readiness",
    "implementation",
    "runtime/API/schema/package behavior change",
    "blocker resolution",
    "dependency closure",
    "None are authorized by this boundary.",
  ]);

  assertIncludesAll(sectionBetween("## Evidence Limits", "## No-Overclaim Rules"), [
    "No-overclaim/status-preservation boundary is not token application.",
    "No-overclaim/status-preservation boundary is not status application.",
    "No-overclaim/status-preservation boundary is not new token groups.",
    "No-overclaim/status-preservation boundary is not new status families.",
    "No-overclaim/status-preservation boundary is not actual label creation.",
    "No-overclaim/status-preservation boundary is not applied status.",
    "No-overclaim/status-preservation boundary is not runtime/product/delivery status application.",
    "No-overclaim/status-preservation boundary is not route creation.",
    "No-overclaim/status-preservation boundary is not route execution.",
    "No-overclaim/status-preservation boundary is not External Reviewer-facing wording.",
    "No-overclaim/status-preservation boundary is not external-use wording.",
    "No-overclaim/status-preservation boundary is not product language.",
    "No-overclaim/status-preservation boundary is not delivery communication.",
    "No-overclaim/status-preservation boundary is not packet wording.",
    "No-overclaim/status-preservation boundary is not finding/severity/remediation/closure wording.",
    "No-overclaim/status-preservation boundary is not technical evidence.",
    "No-overclaim/status-preservation boundary is not CI evidence.",
    "No-overclaim/status-preservation boundary is not runtime certification.",
    "No-overclaim/status-preservation boundary is not technical sign-off.",
    "No-overclaim/status-preservation boundary is not release approval.",
    "No-overclaim/status-preservation boundary is not External Reviewer approval.",
    "No-overclaim/status-preservation boundary is not product candidate.",
    "No-overclaim/status-preservation boundary is not external-use authorization.",
    "Preserved wording/status family is vocabulary only.",
    "Token vocabulary is not actual label creation.",
    "Token vocabulary is not applied status.",
    "Token vocabulary is not runtime/product/delivery status application.",
    "Token vocabulary is not route behavior.",
    "Token vocabulary is not evidence or CI.",
    "Validation output for this doc-freeze slice is not CI evidence.",
    "Test evidence remains tested-scenario evidence, not runtime certainty.",
    "Green tests do not mean release approval.",
    "Local logs are not CI evidence.",
    "Local logs are not packet components.",
    "Generated PDF is not repo evidence.",
    "Generated PDF is not packet component.",
    "DOCS_ONLY boundaries are not runtime enforcement.",
    "Product candidate requires separate explicit selection.",
    "External-use requires separate explicit authorization.",
    "Human/professional review remains release gate.",
    "Continued pause is valid.",
  ]);

  assertIncludesAll(sectionBetween("## No-Overclaim Rules", "## External Reviewer Posture"), [
    "Preserved wording/status family does not mean authorization.",
    "Preserved wording/status family does not mean token application.",
    "Preserved wording/status family does not mean status application.",
    "Preserved wording/status family does not mean actual labels.",
    "Preserved wording/status family does not mean applied status labels.",
    "Preserved wording/status family does not mean runtime/product/delivery status application.",
    "Preserved wording/status family does not mean route behavior.",
    "Preserved wording/status family does not mean evidence or CI evidence.",
    "Preserved wording/status family does not mean External Reviewer-facing wording.",
    "Preserved wording/status family does not mean external-use wording.",
    "Preserved wording/status family does not mean product language.",
    "Preserved wording/status family does not mean delivery or packet language.",
    "Preserved wording/status family does not mean finding, severity, remediation, closure, or blocker-resolution language.",
    "Status-token vocabulary does not create examples, candidates, or test material.",
    "Allowed token group remains vocabulary-only.",
    "Prohibited token group remains overclaim-exclusion only.",
    "Future-authorization-required token group remains future-only.",
    "Non-evidence token group remains non-evidence only.",
    "Non-runtime/non-enforcement token group remains non-runtime/non-enforcement only.",
    "Future proof-test needs do not mean proof tests exist.",
    "Implementation evidence absence does not mean implementation evidence exists.",
    "Blocker visibility does not close blockers.",
    "Closure criteria do not mean closure.",
    "Any future new token groups require separate explicit authorization.",
    "Any future new status families require separate explicit authorization.",
    "Any future token application requires separate explicit authorization.",
    "Any future status application requires separate explicit authorization.",
    "Any future implementation requires separate explicit authorization.",
  ]);

  assertIncludesAll(sectionBetween("## External Reviewer Posture", "## Recommended Next Posture"), [
    "No external-review request is required by this boundary.",
    "Should we freeze a DOCS_ONLY status-family post-wording-consistency no-overclaim/status-preservation boundary after the wording/communication consistency scope",
    "internal scope-control wording only",
    "not a External Reviewer-facing message",
    "external-review requirements remains advisory context only",
  ]);

  assertIncludesAll(sectionBetween("## Recommended Next Posture", null), [
    "REVIEW_ONLY_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY",
    "DOCS_ONLY_NEW_THREAD_HANDOFF_REFRESH_AFTER_STATUS_FAMILY_POST_WORDING_CONSISTENCY_NO_OVERCLAIM_STATUS_PRESERVATION_SCOPE_AFTER_STATUS_FAMILY_POST_APPLICATION_RISK_WORDING_COMMUNICATION_CONSISTENCY_SCOPE_BOUNDARY",
    "continued pause",
    "None are authorized by this boundary.",
  ]);
});

test("boundary rejects exact overclaiming tokens", () => {
  const forbiddenTokens = [
    "STATUS_PRESERVATION_CREATES_NEW_TOKEN_GROUPS",
    "STATUS_PRESERVATION_CREATES_NEW_STATUS_FAMILIES",
    "STATUS_PRESERVATION_APPLIES_TOKENS",
    "STATUS_PRESERVATION_APPLIES_STATUS",
    "STATUS_PRESERVATION_CREATES_ACTUAL_LABELS",
    "STATUS_PRESERVATION_APPLIES_STATUS_LABELS",
    "STATUS_PRESERVATION_APPLIES_RUNTIME_STATUS",
    "STATUS_PRESERVATION_APPLIES_PRODUCT_STATUS",
    "STATUS_PRESERVATION_APPLIES_DELIVERY_STATUS",
    "STATUS_PRESERVATION_CREATES_ROUTES",
    "STATUS_PRESERVATION_EXECUTES_ROUTES",
    "STATUS_PRESERVATION_CREATES_TECHNICAL_EVIDENCE",
    "STATUS_PRESERVATION_CREATES_CI_EVIDENCE",
    "STATUS_PRESERVATION_CREATES_EXTERNAL_REVIEWER_FACING_WORDING",
    "STATUS_PRESERVATION_CREATES_EXTERNAL_USE_WORDING",
    "STATUS_PRESERVATION_CREATES_PRODUCT_LANGUAGE",
    "STATUS_PRESERVATION_CREATES_DELIVERY_COMMUNICATION",
    "STATUS_PRESERVATION_CREATES_PACKET_WORDING",
    "STATUS_PRESERVATION_CREATES_FINDING_WORDING",
    "STATUS_PRESERVATION_CREATES_SEVERITY_WORDING",
    "STATUS_PRESERVATION_CREATES_REMEDIATION_WORDING",
    "STATUS_PRESERVATION_CREATES_CLOSURE_WORDING",
    "STATUS_PRESERVATION_CREATES_BLOCKER_RESOLUTION_WORDING",
    "NO_OVERCLAIM_STATUS_PRESERVATION_CREATES_AUTHORIZATION",
    "NO_OVERCLAIM_STATUS_PRESERVATION_CREATES_RUNTIME_BEHAVIOR",
    "NO_OVERCLAIM_STATUS_PRESERVATION_CREATES_PRODUCT_READY_STATUS",
    "NO_OVERCLAIM_STATUS_PRESERVATION_CREATES_EXTERNAL_USE_READY_STATUS",
    "WORDING_COMMUNICATION_CREATES_EXTERNAL_REVIEWER_FACING_WORDING",
    "WORDING_COMMUNICATION_SENDS_EXTERNAL_REVIEWER_MESSAGE",
    "WORDING_COMMUNICATION_CREATES_EXTERNAL_USE_WORDING",
    "WORDING_COMMUNICATION_CREATES_PRODUCT_LANGUAGE",
    "WORDING_COMMUNICATION_CREATES_DELIVERY_COMMUNICATION",
    "WORDING_COMMUNICATION_CREATES_PACKET_WORDING",
    "EXTERNAL_REVIEWER_FACING_WORDING_CREATED",
    "EXTERNAL_REVIEWER_MESSAGE_CREATED",
    "EXTERNAL_REVIEWER_MESSAGE_SENT",
    "EXTERNAL_USE_WORDING_CREATED",
    "PRODUCT_LANGUAGE_CREATED",
    "DELIVERY_COMMUNICATION_CREATED",
    "PACKET_WORDING_CREATED",
    "FINDING_WORDING_CREATED",
    "SEVERITY_WORDING_CREATED",
    "REMEDIATION_WORDING_CREATED",
    "CLOSURE_WORDING_CREATED",
    "BLOCKER_RESOLUTION_WORDING_CREATED",
    "TOKEN_APPLICATION_CREATED",
    "TOKEN_APPLIED",
    "STATUS_APPLICATION_CREATED",
    "STATUS_APPLIED",
    "ACTUAL_LABEL_APPLIED",
    "RUNTIME_STATUS_APPLIED",
    "PRODUCT_STATUS_APPLIED",
    "DELIVERY_STATUS_APPLIED",
    "ACTUAL_REVIEW_ROUTE_CREATED",
    "REVIEW_ROUTE_EXECUTED",
    "RUNTIME_ROUTE_CREATED",
    "WORKFLOW_ROUTE_CREATED",
    "SCHEMA_ROUTE_CREATED",
    "DELIVERY_ROUTE_CREATED",
    "PACKET_ROUTE_CREATED",
    "PRODUCT_EXTERNAL_USE_ROUTE_CREATED",
    "CANDIDATE_ROUTE_CREATED",
    "CANDIDATE_EXAMPLES_SELECTED",
    "CANDIDATE_EXAMPLES_INCLUDED",
    "EXAMPLE_CANDIDATE_TEXT_DEFINED",
    "SYNTHETIC_CANDIDATE_SELECTED",
    "ACTUAL_TEST_MATERIAL_SELECTED",
    "LOCAL_SANITIZED_TEST_PILOT_AUTHORIZED",
    "LOCAL_SANITIZED_TEST_PILOT_EXECUTED",
    "REAL_PRIVATE_RUN_AUTHORIZED",
    "REAL_PRIVATE_RUN_STARTED",
    "TECHNICAL_EVIDENCE_CREATED",
    "CI_EVIDENCE_EXISTS",
    "CI_EVIDENCE_CREATED",
    "TEST_OUTPUT_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOGS_CAPTURED_AS_EVIDENCE",
    "LOCAL_LOG_INSPECTION_AUTHORIZED",
    "LOCAL_LOGS_ARE_CI_EVIDENCE",
    "LOCAL_LOGS_ARE_PACKET_COMPONENTS",
    "RAW_PRIVATE_SOURCE_INSPECTION_AUTHORIZED",
    "SOURCE_PACKAGE_INSPECTION_AUTHORIZED",
    "PDF_IMAGE_SCREENSHOT_METADATA_INSPECTION_AUTHORIZED",
    "METADATA_ACQUISITION_AUTHORIZED",
    "RELEASE_APPROVAL_CREATED",
    "RUNTIME_CERTIFICATION_CREATED",
    "TECHNICAL_SIGN_OFF_CREATED",
    "EXTERNAL_REVIEWER_APPROVAL_CREATED",
    "PRODUCT_CANDIDATE_SELECTED",
    "EXTERNAL_USE_AUTHORIZED",
    "DELIVERY_TO_EXTERNAL_REVIEWER_AUTHORIZED",
    "PACKET_APPROVAL_CREATED",
    "FINAL_DELIVERY_DECISION_CREATED",
    "PDF_PACKET_CREATED",
    "ARCHIVE_ZIP_CREATED",
    "PDF_CREATED",
    "ZIP_CREATED",
    "LEGAL_CONCLUSION_CREATED",
    "CLINICAL_CONCLUSION_CREATED",
    "EVIDENTIARY_CONCLUSION_CREATED",
    "CASE_TRUTH_CONCLUSION_CREATED",
    "CREDIBILITY_FINDING_CREATED",
    "RISK_SCORE_CREATED",
    "SUFFICIENCY_SCORE_CREATED",
    "POLICE_REPORT_CREATED",
    "PLEADING_CREATED",
    "IMPLEMENTATION_EVIDENCE_EXISTS",
    "IMPLEMENTATION_READINESS_AUTHORIZED",
    "IMPLEMENTATION_AUTHORIZED",
    "RUNTIME_AUTHORIZED",
    "RUNTIME_READY",
    "MODEL_RUNTIME_READY",
    "MODEL_COMPLETE",
    "MODEL_COMPLETION_READY",
    "BLOCKER_RESOLVED",
    "DEPENDENCY_CLOSED",
    "SECURITY_FINDING_CREATED",
    "VULNERABILITY_FINDING_CREATED",
    "SEVERITY_ASSIGNED",
    "REMEDIATION_RECOMMENDED",
    "REMEDIATION_IMPLEMENTED",
  ];

  for (const token of forbiddenTokens) {
    assertDoesNotIncludeExactToken(doc, token);
  }
});
