const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const docsPath = path.join(
  __dirname,
  "..",
  "docs",
  "DOMAIN_CONTRACTS_MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_BOUNDARY_v1.md",
);
const docsText = fs.readFileSync(docsPath, "utf8");

function assertIncludesAll(entries, text = docsText) {
  for (const entry of entries) {
    assert.match(
      text,
      new RegExp(entry.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"),
    );
  }
}

test("minimum viable trust spine evidence and closure-plan boundary doc exists", () => {
  assert.equal(fs.existsSync(docsPath), true);
});

test("identity and status tokens exist", () => {
  assertIncludesAll([
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_BOUNDARY",
    "DOCS_ONLY",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_ONLY",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_FUTURE_EVIDENCE_ONLY",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_PARTIAL_GAP_CONTEXT",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_NON_AUTHORIZING",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_NOT_IMPLEMENTATION_READINESS_AUTHORIZATION",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_NOT_IMPLEMENTATION",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_NOT_RUNTIME_BEHAVIOR",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_NOT_RUNTIME_API_SCHEMA_PACKAGE_BEHAVIOR_CHANGE",
    "TRUST_SPINE_A_DENY_BY_DEFAULT_POLICY_RESOURCE_MATERIAL_CLASS_KERNEL",
    "TRUST_SPINE_B_NO_CONTENT_DECISION_EVENT_TAXONOMY",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_STATUS_GAP_CONTEXT",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_IMPLEMENTATION_READINESS_AUTHORIZATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_POLICY_KERNEL_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_POLICY_EVALUATOR_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_DECISION_EVENT_TAXONOMY_RUNTIME_CODE",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_EVENT_EMITTER",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_LOG_SCHEMA",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_LOG_STORAGE",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_RBAC_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_ADMIN_SUPPORT_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_AUDIT_ACCESS_LOG_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_RETENTION_DELETION_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_RAW_MATERIAL_ROUTING_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_THIRD_PARTY_ROUTING_AUTHORIZATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_RUNTIME_GATE_IMPLEMENTATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_VALIDATOR_DISPATCH",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_REGISTRY_LOOKUP",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_CI_EVIDENCE_CREATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_RELEASE_APPROVAL",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_PRODUCT_CANDIDATE",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_EXTERNAL_USE_AUTHORIZATION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_BLOCKER_RESOLUTION",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_NOT_DEPENDENCY_CLOSURE",
    "TRUST_SPINE_A_AND_B_EVIDENCE_CLOSURE_PLAN_CONTINUED_PAUSE",
  ]);
});

test("required sections and posture statements exist", () => {
  assertIncludesAll([
    "## Purpose",
    "This boundary freezes future evidence and closure-plan requirements after the DOCS_ONLY status/gap boundary.",
    "PARTIAL_GAP_REQUIRES_DOCS_ONLY_MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_STATUS_GAP_BOUNDARY",
    "A+B remains partial/gap and non-authorizing.",
    "This boundary creates no implementation-readiness authorization.",
    "This boundary creates no implementation.",
    "This boundary creates no runtime/API/schema/package behavior change.",
    "This boundary creates no policy kernel, policy evaluator, decision-event taxonomy runtime code, event emitter, log schema, or log storage.",
    "Evidence plan does not mean evidence exists.",
    "Closure plan does not mean closure.",
    "Closure criteria do not mean closure.",
    "Any future implementation or implementation-readiness authorization requires a separate explicit user-authorized scope after live git guard.",
  ]);
});

test("source hierarchy exists", () => {
  assertIncludesAll([
    "LIVE_REPO_EVIDENCE_WINS",
    "TRACKED_REPO_EVIDENCE_CONTROLS_CURRENT_STATE",
    "NEW_THREAD_HANDOFF_FILE_IS_CONTEXT_ONLY",
    "IMPLEMENTATION_READINESS_ENTRY_CRITERIA_BOUNDARY_CONTROLS_ENTRY_RULES",
    "MINIMUM_VIABLE_TRUST_SPINE_STATUS_GAP_BOUNDARY_CONTROLS_A_AND_B_STATUS_GAP",
    "MINIMUM_VIABLE_TRUST_SPINE_ENTRY_CANDIDATE_SCOPE_BOUNDARY_CONTROLS_A_AND_B_SCOPE",
    "MINIMUM_VIABLE_TRUST_SPINE_STRATEGY_BOUNDARY_CONTROLS_A_AND_B_STRATEGY",
    "FINAL_BLOCKED_CHAIN_STATUS_BOUNDARY_CONTROLS_CURRENT_BLOCKED_CHAIN_CONTEXT",
    "POST_RUNTIME_GATE_BLOCKED_COMPLETION_SUMMARY_BOUNDARY_CONTROLS_POST_RUNTIME_GATE_CONTEXT",
    "DATA_HANDLING_SECURITY_CONTROL_PLANE_PLANNING_ROUND_SUMMARY_CONTROLS_DHC_CONTEXT",
    "RUNTIME_GATE_IMPLEMENTATION_CANDIDATE_INVENTORY_PLANNING_ROUND_SUMMARY_BOUNDARY_CONTROLS_RUNTIME_GATE_CONTEXT",
    "ROADMAP_DEPENDENCIES_001_TO_007_BLOCKED_COMPLETION_ROUND_SUMMARY_CONTROLS_DEPENDENCY_CONTEXT",
    "RBAC_ADMIN_SUPPORT_BOUNDARY_DOCS_CONTROL_ACCESS_CONTEXT",
    "AUDIT_ACCESS_LOG_BOUNDARY_DOCS_CONTROL_AUDIT_CONTEXT",
    "RETENTION_DELETION_BOUNDARY_DOCS_CONTROL_LIFECYCLE_CONTEXT",
    "RAW_MATERIAL_ROUTING_BOUNDARY_DOCS_CONTROL_RAW_ROUTING_CONTEXT",
    "THIRD_PARTY_PROVIDER_BOUNDARY_DOCS_CONTROL_PROVIDER_CONTEXT",
    "EXTERNAL_REVIEW_REQUIREMENTS_USED_AS_ADVISORY_CONTEXT_ONLY",
    "OLD_HANDOFF_FILES_ARE_HISTORICAL_CONTEXT_ONLY",
    "STALE_HANDOFF_MUST_NOT_SELECT_REOPEN_OR_CLOSE_SLICE",
  ]);
});

test("current accepted state and prior status gap result exist", () => {
  assertIncludesAll([
    "97c9b05 docs(context): refresh new-thread handoff after trust spine status gap",
    "07fe867 docs(domain): freeze trust spine implementation-readiness status gap boundary",
    "MINIMUM_VIABLE_TRUST_SPINE_STATUS_GAP_BOUNDARY_AND_HANDOFF_REFRESH_REVIEWED_AND_PAUSED_NO_CHANGE",
    "NEXT_SAFE_POSTURE_SELECTED_AFTER_MINIMUM_VIABLE_TRUST_SPINE_STATUS_GAP_HANDOFF_REFRESH_PAUSE_NO_CHANGE",
    "COMBINED_READ_ONLY_MINIMUM_VIABLE_TRUST_SPINE_STATUS_GAP_HANDOFF_REFRESH_PAUSE_AND_NEXT_SAFE_POSTURE_SELECTION_COMPLETED_NO_CHANGE",
    "The current safe posture remains continued pause until a separate next posture is selected.",
    "The PROVE_ONLY minimum viable trust spine implementation-readiness status/gap review was performed.",
    "The DOCS_ONLY status/gap boundary was frozen and reviewed.",
    "A future evidence/closure-plan boundary is suitable.",
    "This boundary freezes future requirements only.",
    "This boundary does not alter status/gap into implementation-readiness authorization, implementation, runtime behavior, CI evidence, release approval, product candidate, external-use authorization, blocker closure, or dependency closure.",
  ]);
});

test("evidence and closure-plan matrix and all rows exist", () => {
  assertIncludesAll([
    "## Evidence And Closure-Plan Matrix",
    "row ID",
    "evidence/closure surface",
    "current status/gap reference",
    "required future implementation or authorization evidence",
    "required future test evidence",
    "required future CI evidence if claimed",
    "closure criteria",
    "evidence limit",
    "what remains non-authorized until closure",
    "Every row preserves evidence/closure-plan only, future evidence only, partial/gap where applicable, no implementation-readiness authorization, no implementation, no runtime/API/schema/package behavior change, no policy kernel, no policy evaluator, no decision-event runtime code, no event emitter, no log schema, no log storage, no CI evidence, no release approval, no product candidate, no external-use, no blocker resolution, no dependency closure, and continued pause.",
    ...Array.from({ length: 31 }, (_, index) =>
      `MVTSP-ECP-${String(index + 1).padStart(3, "0")}`,
    ),
  ]);
});

test("future implementation authorization evidence requirements exist", () => {
  assertIncludesAll([
    "## Required Future Implementation Or Authorization Evidence",
    "explicit user-authorized implementation or implementation-readiness scope after live git guard",
    "tracked implementation diff",
    "mapped doc/contract reference",
    "mapped test reference",
    "no raw/private/source inspection unless separately authorized",
    "no source package inspection unless separately authorized",
    "no PDF/image/screenshot/metadata inspection unless separately authorized",
    "no local log promotion to CI evidence or packet component",
    "no product/external-use/release implication",
    "review-only evidence acceptance step before any closure claim",
    "None of these evidence items exist because of this boundary.",
  ]);
});

test("future test and CI evidence requirements exist", () => {
  assertIncludesAll([
    "## Required Future Test And CI Evidence",
    "default-deny tests",
    "allow/deny tests",
    "wrong-tenant tests",
    "wrong-case tests",
    "wrong-object/function/property tests",
    "wrong-material-class tests",
    "no-raw/no-private/no-source-locator/no-token/no-URL tests",
    "no-content decision-event tests",
    "reason-code tests",
    "event taxonomy tests",
    "event emitter tests if ever implemented",
    "log schema tests if ever implemented",
    "log storage tests if ever implemented",
    "RBAC/admin-support tests if ever implemented",
    "audit/access-log tests if ever implemented",
    "retention/deletion lifecycle tests if ever implemented",
    "raw-routing deny/quarantine tests if ever implemented",
    "third-party/provider deny-by-default tests if ever implemented",
    "runtime-gate prerequisite tests if ever implemented",
    "no-overclaim proof tests",
    "CI evidence only if separately created and claimed",
    "Local tests are not CI evidence.",
    "Green tests are not release approval.",
    "Tests remain tested-scenario evidence unless separately elevated with explicit evidence and review.",
  ]);
});

test("closure criteria exist", () => {
  assertIncludesAll([
    "## Closure Criteria",
    "explicit implementation or implementation-readiness authorization",
    "tracked implementation evidence where implementation is claimed",
    "passing focused tests for the claimed behavior",
    "CI evidence only if CI-backed claims are made",
    "no-overclaim review",
    "human/professional review gate preserved",
    "product candidate still separate",
    "external-use still separate",
    "delivery/packet approval still separate",
    "blockers explicitly resolved by tracked evidence",
    "dependencies explicitly closed by tracked evidence",
    "closure review in a separate explicitly authorized pass",
    "Closure criteria do not mean closure.",
    "This boundary resolves no blocker and closes no dependency.",
  ]);
});

test("candidate surface and blocker coverage summaries exist", () => {
  assertIncludesAll([
    "## Candidate Surface Summary",
    "A covers deny-by-default policy/resource/material-class vocabulary.",
    "B covers no-content decision-event taxonomy.",
    "actor/subject",
    "role/permission concept",
    "tenant/case scope",
    "object/function/property scope",
    "material class",
    "route/surface",
    "action",
    "allow/deny",
    "default deny",
    "reason code",
    "no-raw/no-private/no-source-locator/no-token/no-URL posture",
    "subject reference",
    "decision status",
    "timestamp category",
    "no-raw/no-private/no-source-locator marker",
    "no raw content",
    "no private facts",
    "no source locators",
    "no token/URL/secret material",
    "These remain evidence/closure-plan fields only.",
    "These are not schema, runtime code, event emitter, log schema, log storage, policy evaluator, implementation evidence, test closure evidence, or CI evidence.",
    "## Blocker Coverage Summary",
    "A+B supports D001 RBAC/admin-support vocabulary.",
    "A+B supports D002 audit/access-log event semantics.",
    "A+B supports D003 retention/deletion lifecycle decisions.",
    "A+B supports D004 raw-material routing deny/quarantine decisions.",
    "A+B supports D005 third-party/provider deny-by-default routing posture.",
    "A+B supports D006 validator/registry/runtime-gate prerequisites later.",
    "A+B supports D007 CI/release/product/external-use gate evidence later.",
    "A+B supports DHC future evidence and closure criteria.",
    "A+B should precede runtime gates.",
    "A+B can be scoped without raw/private/source inspection.",
    "A+B can be scoped without source package inspection.",
    "A+B can be scoped without PDF/image/screenshot/metadata inspection.",
    "A+B can be scoped without metadata acquisition.",
    "A+B can be scoped without local log inspection.",
    "A+B can be scoped without real private run.",
    "All blockers remain unresolved/not closed.",
  ]);
});

test("required non-authorizations and evidence limits exist", () => {
  assertIncludesAll([
    "## Required Non-Authorizations",
    "implementation-readiness",
    "implementation",
    "runtime behavior",
    "runtime/API/schema/package behavior change",
    "policy kernel implementation",
    "policy evaluator implementation",
    "decision-event taxonomy runtime code",
    "event emitter",
    "log schema",
    "log storage",
    "RBAC implementation",
    "admin/support implementation",
    "audit/access-log implementation",
    "retention implementation",
    "deletion implementation",
    "raw-material routing implementation",
    "third-party routing implementation or authorization",
    "provider integration",
    "provider registry",
    "provider status implementation",
    "data-routing map implementation",
    "token/URL/secret handling implementation",
    "runtime gate implementation",
    "runtime gate inventory as implementation",
    "validator dispatch",
    "registry/lookup",
    "CI evidence",
    "release approval",
    "runtime certification",
    "technical sign-off",
    "External Reviewer approval",
    "product candidate",
    "external-use authorization",
    "delivery to External Reviewer",
    "packet approval",
    "final delivery decision",
    "PDF packet",
    "archive/ZIP",
    "raw/private/source inspection",
    "source package inspection",
    "PDF/image/screenshot/metadata inspection",
    "metadata acquisition",
    "real private run",
    "blocker resolution",
    "dependency closure",
    "finding",
    "severity",
    "remediation",
    "## Evidence Limits",
    "evidence/closure-plan boundary is not implementation-readiness authorization",
    "evidence/closure-plan boundary is not implementation",
    "evidence/closure-plan boundary is not implementation evidence",
    "evidence plan does not mean evidence exists",
    "closure plan does not mean closure",
    "closure criteria do not mean closure",
    "tests remain tested-scenario evidence, not runtime certainty",
    "local logs are not CI evidence",
    "local logs are not packet components",
    "green tests are not release approval",
    "DOCS_ONLY boundaries are not runtime enforcement",
    "route/case/capability evidence is not full RBAC/access-control",
    "route/case/capability evidence is not admin/support access-control",
    "route/case/capability evidence is not global authorization model",
    "runtime gate inventory is not implementation",
    "CI evidence requires separate explicit CI evidence creation",
    "product candidate requires separate explicit selection",
    "external-use requires separate explicit authorization",
    "human/professional review remains release gate",
    "continued pause is valid",
  ]);
});

test("no-overclaim rules, External Reviewer posture, and recommended next posture exist", () => {
  assertIncludesAll([
    "## No-Overclaim Rules",
    "evidence/closure-plan boundary does not mean implementation-readiness authorization",
    "evidence/closure-plan boundary does not mean implementation",
    "evidence/closure-plan boundary does not mean policy kernel exists",
    "evidence/closure-plan boundary does not mean policy evaluator exists",
    "evidence/closure-plan boundary does not mean event taxonomy runtime code exists",
    "evidence/closure-plan boundary does not mean event emitter exists",
    "evidence/closure-plan boundary does not mean log schema exists",
    "evidence/closure-plan boundary does not mean log storage exists",
    "evidence/closure-plan boundary does not mean RBAC exists",
    "evidence/closure-plan boundary does not mean audit/access-log exists",
    "evidence/closure-plan boundary does not mean retention/deletion exists",
    "evidence/closure-plan boundary does not mean raw routing exists",
    "evidence/closure-plan boundary does not mean third-party provider registry exists",
    "evidence/closure-plan boundary does not mean runtime gates exist",
    "evidence/closure-plan boundary does not mean CI evidence exists",
    "evidence/closure-plan boundary does not mean release approval",
    "evidence/closure-plan boundary does not mean product candidate",
    "evidence/closure-plan boundary does not mean external-use authorization",
    "evidence/closure-plan boundary does not mean blocker closure",
    "evidence/closure-plan boundary does not mean dependency closure",
    "required evidence does not mean evidence exists",
    "required tests do not mean tests exist",
    "required CI does not mean CI exists",
    "closure criteria do not mean closure",
    "any future implementation-readiness authorization requires separate explicit authorization",
    "any future implementation requires separate explicit authorization",
    "## External Reviewer Posture",
    "No external-review request is required by this boundary.",
    "Should the minimum viable trust spine implementation-readiness evidence and closure plan remain the controlling non-authorizing prerequisite before any later implementation-readiness authorization or implementation slice?",
    "external-review requirements remains advisory context only, not approval, sign-off, implementation-readiness authorization, implementation authorization, release approval, product candidate, or external-use authorization.",
    "## Recommended Next Posture",
    "REVIEW_ONLY_MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_EVIDENCE_AND_CLOSURE_PLAN_BOUNDARY",
    "MINIMUM_VIABLE_TRUST_SPINE_IMPLEMENTATION_READINESS_PLANNING_ROUND_STATUS_LOCK",
    "continued pause",
    "None are authorized by this boundary.",
  ]);
});

test("boundary rejects exact overclaiming tokens", () => {
  const forbiddenTokens = [
    "TRUST_SPINE_IMPLEMENTATION_READY",
    "TRUST_SPINE_READY_FOR_IMPLEMENTATION",
    "TRUST_SPINE_IMPLEMENTED",
    "TRUST_SPINE_CLOSED",
    "TRUST_SPINE_BLOCKER_RESOLVED",
    "EVIDENCE_PLAN_AUTHORIZES_IMPLEMENTATION_READINESS",
    "EVIDENCE_PLAN_AUTHORIZES_IMPLEMENTATION",
    "CLOSURE_PLAN_CREATES_CLOSURE",
    "CLOSURE_CRITERIA_MET",
    "POLICY_KERNEL_CREATED",
    "POLICY_KERNEL_IMPLEMENTED",
    "POLICY_EVALUATOR_CREATED",
    "POLICY_EVALUATOR_IMPLEMENTED",
    "DECISION_EVENT_TAXONOMY_CREATED",
    "DECISION_EVENT_TAXONOMY_IMPLEMENTED",
    "EVENT_EMITTER_CREATED",
    "LOG_SCHEMA_CREATED",
    "LOG_STORAGE_CREATED",
    "RBAC_IMPLEMENTED",
    "ADMIN_SUPPORT_IMPLEMENTED",
    "RETENTION_IMPLEMENTED",
    "DELETION_IMPLEMENTED",
    "AUDIT_ACCESS_LOG_IMPLEMENTED",
    "RAW_MATERIAL_ROUTING_IMPLEMENTED",
    "THIRD_PARTY_ROUTING_AUTHORIZED",
    "THIRD_PARTY_ROUTING_IMPLEMENTED",
    "PROVIDER_INTEGRATION_CREATED",
    "PROVIDER_REGISTRY_CREATED",
    "PROVIDER_STATUS_IMPLEMENTATION_CREATED",
    "DATA_ROUTING_MAP_CREATED",
    "TOKEN_URL_SECRET_HANDLING_IMPLEMENTED",
    "RUNTIME_GATE_IMPLEMENTED",
    "RUNTIME_GATE_INVENTORY_IMPLEMENTED",
    "VALIDATOR_DISPATCH_CREATED",
    "REGISTRY_LOOKUP_CREATED",
    "IMPLEMENTATION_EVIDENCE_EXISTS",
    "TEST_EVIDENCE_EXISTS",
    "CI_EVIDENCE_EXISTS",
    "IMPLEMENTATION_READINESS_AUTHORIZED",
    "IMPLEMENTATION_AUTHORIZED",
    "RUNTIME_AUTHORIZED",
    "RUNTIME_READY",
    "MODEL_RUNTIME_READY",
    "MODEL_COMPLETE",
    "MODEL_COMPLETION_READY",
    "CI_EVIDENCE_CREATED",
    "RELEASE_APPROVAL_CREATED",
    "RUNTIME_CERTIFICATION_CREATED",
    "TECHNICAL_SIGN_OFF_CREATED",
    "EXTERNAL_REVIEWER_APPROVAL_CREATED",
    "PRODUCT_CANDIDATE_SELECTED",
    "EXTERNAL_USE_AUTHORIZED",
    "DELIVERY_TO_EXTERNAL_REVIEWER_AUTHORIZED",
    "PACKET_APPROVAL_CREATED",
    "FINAL_DELIVERY_DECISION_CREATED",
    "PDF_PACKET_CREATED",
    "ARCHIVE_ZIP_CREATED",
    "RAW_PRIVATE_SOURCE_INSPECTION_AUTHORIZED",
    "SOURCE_PACKAGE_INSPECTION_AUTHORIZED",
    "PDF_IMAGE_SCREENSHOT_METADATA_INSPECTION_AUTHORIZED",
    "METADATA_ACQUISITION_AUTHORIZED",
    "REAL_PRIVATE_RUN_AUTHORIZED",
    "BLOCKER_RESOLVED",
    "DEPENDENCY_CLOSED",
    "SECURITY_FINDING_CREATED",
    "VULNERABILITY_FINDING_CREATED",
    "SEVERITY_ASSIGNED",
    "REMEDIATION_RECOMMENDED",
    "REMEDIATION_IMPLEMENTED",
  ];

  for (const token of forbiddenTokens) {
    assert.equal(
      docsText.includes(token),
      false,
      `Boundary doc must not include overclaiming token ${token}`,
    );
  }
});
